#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib";
use ForseeAtomPos;

#
# Creates standard mmcif output with only _atom_site category and checks,
# if all data was correctly obtained.
#

my @atom_site = @{ ForseeAtomPos::obtain_atom_site( <> ) };
my @attribute_names = @{ $atom_site[0] };
my @attribute_data =  @{ $atom_site[1] };

print "loop_\n";

foreach( @attribute_names ){
    print "_atom_site." . $_ . "\n";
}

for( my $i = 0; $i < $#attribute_data + 1; $i++ ){
    if( $i % ( $#attribute_names + 1) != 0 ){
        print " ", $attribute_data[$i], " ";
    }else{
        print "\n", $attribute_data[$i];
    }
}
