#!/usr/bin/perl

use strict;
use warnings;

use ForceField::Parameters;
use PDBxParser qw( to_pdbx );

#
# Test tool: dump_to_cif
# Example: ./dump_to_cif structure.dump
#

@ARGV = ( "-" ) unless @ARGV;

my $parameters = Parameters->new();

foreach my $pdbx_dump_file ( @ARGV ) {
    my $atom_site;
    open( my $fh, "<", $pdbx_dump_file );
    while( <$fh> ) {
        $atom_site .= "$_" ;
    }
    close( $fh );
    $atom_site = eval( $atom_site );

    my %pdbx =();
    $pdbx{'_atom_site'}{'data'} = $atom_site;
    $pdbx{'_atom_site'}{'metadata'}{'is_loop'} = 1;
    $pdbx{'_atom_site'}{'metadata'}{'type'} = 'indexed';

    to_pdbx( \%pdbx );
}
