#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;
use Getopt::Long;

use ConnectAtoms qw( connect_atoms );
use BondProperties qw( hybridization );
use PDBxParser qw( obtain_atom_site );
use SidechainModels qw( rotation_only );

$Data::Dumper::Indent = 1;
$Data::Dumper::Sortkeys = 1;

#
# Test tool: dump_cif_structure
# Example: ./dump_cif_structure structure.cif
#

my %options;

my $is_connected = 0;
my $is_hybridized = 0;
my $apply_rotation_only = 0;

GetOptions(
    "c" => sub { $is_connected = 1 },
    "h" => sub { $is_hybridized = 1 },
    "r" => sub { $apply_rotation_only = 1 },
) or die "Error in command line argument.";

@ARGV = ( "-" ) unless @ARGV;

my $atom_site;

foreach my $pdbx_file ( @ARGV ) {
    $atom_site = obtain_atom_site( $pdbx_file );

    if( $is_connected ) {
        connect_atoms( $atom_site );
    }

    if( $is_hybridized ) {
        hybridization( $atom_site );
    }

    if( $apply_rotation_only ) {
        rotation_only( $atom_site );
    }

    my $cif_dump_structure = Dumper( $atom_site );
    $cif_dump_structure =~ s/\$VAR[0..9]*.*=\s*//g;
    $cif_dump_structure =~ s/};/}/g;
    print( $cif_dump_structure );
}
