site_name: "rotag"
theme:
    name: material
    features:
        - navigation.path
        - toc.integrate
    logo: assets/rotag-logo-dark-bg.svg
    favicon: assets/favicon.ico
    icon:
        repo: fontawesome/brands/github
extra_css:
    - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
repo_name: agrybauskas/rotag
nav:
    - Home: 'index.md'
    - Installation: 'installation.md'
    - Documentation:
        - Tutorials:
            - 'Adding hydrogens': 'adding-hydrogens.md'
    - License: 'license.md'
    - Cite: 'cite.md'