site_name: ""
theme:
    name: material
    favicon: assets/favicon.ico
extra_css:
    - stylesheets/extra.css
nav:
    - Home: 'index.md'
    - Installation: 'installation.md'
    - Documentation:
        - Tutorials:
            - 'Adding hydrogens': 'adding-hydrogens.md'
    - License: 'license.md'
    - Cite: 'cite.md'