site_name: ""
site_favicon: favicon.ico
theme:
    name: material
extra_css:
    - css/extra.css
nav:
    - Home: 'index.md'
    - Installation: 'installation.md'
    - Documentation:
        - Tutorials:
            - 'Adding hydrogens': 'adding-hydrogens.md'
    - License: 'license.md'
    - Cite: 'cite.md'