#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use LinearAlgebra;

use lib "../lib";
use Utils;

#
# Unit test:
#
#
# Example: ./rotate_x_axis "id 1,2" "Cartn_x,Cartn_y,Cartn_z" < example.cif
#

my $attribute_filter = shift;
my $attribute_select = shift;
my $angle = shift;
my @cif = <>;

# Selects atom's data for further analysis.
my $selected_atom_data =
    Utils::select_atom_data( $attribute_filter,
			     $attribute_select,
			     @cif );

# Prints out length of the bond in angstroms.
