#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use CifParser;
use SidechainModels;

my $attribute_filter = shift;
my @cif = <>;

# Parses selector argument from string  to proper array.
my @attribute_filter = map { $_->[0] => [ split( ",", @$_[1] ) ] }
                       map { [ split( " ", $_ ) ] }
                       split( "&", $attribute_filter );

my @attribute_select = ();

# Selects atoms for further analysis.
my @selected_atom_data =
    @{ CifParser::select_atom_data( \@attribute_filter,
				    \@attribute_select,
				    @cif ) };

# Applies molecule alterations.
SidechainModels::cf_serine( @attribute_filter );
