#!/usr/bin/perl

use strict;
use warnings;
use Data::Dumper;

use lib "../../lib/perl";
use CifParser;
use ConnectAtoms;

#
# Test program, as argv, uses both attribute filter, attribute data selection
# info and mmCIF. In order test to be flexible, attribute information is
# entered in string form:
#
# "label_atom_id CA,CB & id 147, 148"
#
# and then parsed to such form:
#
# [ "label_atom_id" => [ "CA",  "CB"  ],
#   "id"            => [ "147", "148" ] ].
#
# Attribute data is selected in such form:
#
# "Cartn_x, Cartn_y, Cartn_z"
#
# The third argument is mmCIF format stdin.
#

my $attribute_filter = shift;
my $attribute_select = shift;

# Parses selector argument from string  to proper array.
my @attribute_filter = [ map { $_->[0] => [ split( ",", @$_[1] ) ] }
                         map { [ split( " ", $_ ) ] }
                         split( "&", $attribute_filter ) ];
my @attribute_select = [ split( ",", $attribute_select ) ];

my @selected_atom_data = @{ CifParser::select_atom_data( @attribute_filter,
							 @attribute_select,
							 <> ) };

my @box_boundaries = ConnectAtoms::create_box( @selected_atom_data );

print map { ( $_ % 2 ) == 0
		        ? $box_boundaries[$_-1] . "\n"
			: $box_boundaries[$_-1] . "\t" }
      ( 1..$#box_boundaries + 1 )
