#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use CifParser;
use ConnectAtoms;

#
# Unit test: ConnectAtoms::create_box.
#
# Creates smallest possible box that surrounds all selected atoms.
#
# Example: ./create_box "label_atom_id CA,C,CB,OG" \
#          "id,label_atom_id,label_comp_id,Cartn_x,Cartn_y,Cartn_z" < example.cif
#

my $attribute_filter = shift;
my $attribute_select = shift;

# Parses selector argument from string  to proper array.
my @attribute_filter = [ map { $_->[0] => [ split( ",", @$_[1] ) ] }
                         map { [ split( " ", $_ ) ] }
                         split( "&", $attribute_filter ) ];
my @attribute_select = [ split( ",", $attribute_select ) ];

# Selects atoms for further analysis.
my @selected_atom_data = @{ CifParser::select_atom_data( @attribute_filter,
							 @attribute_select,
							 <> ) };

# Creates and prints out the boundaries of the box.
my @box_boundaries = ConnectAtoms::create_box( @selected_atom_data );

print( map { ( $_ % 2 ) == 0
		        ? $box_boundaries[$_-1] . "\n"
			: $box_boundaries[$_-1] . "\t" }
       ( 1..$#box_boundaries + 1 ) )
