#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;

use lib "../../lib/perl";
use LinearAlgebra;

my $symbols = shift;
my @symbols = [ split( ",", $symbols ) ];
my @matrices = ( [] );

while( <> ) {
    if( $_ =~ /^\n$/ ) {
	push( @matrices, [] );
    } else {
	push( @{ $matrices[-1] }, [ split( " ", $_ ) ] );
    }
}

print LinearAlgebra::dot_product( @symbols, @matrices );

