#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib";
use CifParser;

#
# Test program, as argv, uses both attribute information and mmCIF. In order
# test to be flexible, attribute information is entered in string form:
#
# "label_atom_id CA,CB & id 147, 148"
#
# and then parsed to such form:
#
# [ "label_atom_id" => [ "CA",  "CB"  ],
#   "id"            => [ "147", "148" ] ].
#
# Second argument is mmCIF format stdin.
#

my $attribute_selector = shift;

# Parses selector argument from string  to proper array.
my @attribute_selector = [ map { $_->[0] => [ split( ",", @$_[1] ) ] }
                           map { [ split( " ", $_ ) ] }
                           split( "&", $attribute_selector ) ];

my @filtered_atoms = CifParser::filter_atoms( @attribute_selector, <> );

my @attribute_names = @{ $filtered_atoms[0] };
my @attribute_data =  @{ $filtered_atoms[1] };

print "loop_\n";

foreach( @attribute_names ) {
    print "_atom_site." . $_ . "\n";
}

for( my $i = 0; $i < $#attribute_data + 1; $i++ ) {
    if( $i % ( $#attribute_names + 1 ) != 0 ) {
        print " ", $attribute_data[$i], " ";
    } else {
        print "\n", $attribute_data[$i];
    }
}

print( "\n" );
