#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;

use lib "../../lib/perl";
use LinearAlgebra;

my $symbols = shift;
   $symbols //= ",";
my @symbols = [ split( ",", $symbols ) ];
my @symb_matrices = ( [] );

while( <> ) {
    if( $_ =~ /^\n$/ ) {
	push( @symb_matrices, [] );
    } else {
	push( @{ $symb_matrices[-1] }, [ split( " ", $_ ) ] );
    }
} 

my $symb_dot_product = 
    LinearAlgebra::mult_matrix_product( @symbols,
					@symb_matrices );

foreach( @$symb_dot_product ) {
    print( join( "\t", @$_ ), "\n" );
}
