#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use CifParser;

#
# Unit test: CifParser::select_atom_data.
#
# Selects atom data by given attributes.
#
# Example: ./select_atom_data "label_atom_id CA,N,CB,OG" \
#                             "Cartn_x,Cartn_y,Cartn_z" < example.cif
#

my $attribute_filter = shift;
my $attribute_select = shift;

# Parses selector argument from string  to proper array.
my @attribute_filter = [ map { $_->[0] => [ split( ",", @$_[1] ) ] }
                         map { [ split( " ", $_ ) ] }
                         split( "&", $attribute_filter ) ];
my @attribute_select = [ split( ",", $attribute_select ) ];

# Selects atoms for further analysis.
my @selected_atom_data = @{ CifParser::select_atom_data( @attribute_filter,
							 @attribute_select,
							 <> ) };

for( my $i = 0; $i <= $#selected_atom_data; $i++ ) {
    print( join( " ", @{ $selected_atom_data[$i] } ), "\n" );
}
