#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;

use lib "../../lib";
use ForseeAtomPos;

my @selected_atom_data = @{ ForseeAtomPos::select_atom_data( [ "label_atom_id" => [ "CA", "C", "CB", "OG" ] ],
							     [ "Cartn_x", "Cartn_y", "Cartn_z" ],
							     <> ) };

for( my $i = 0; $i <= $#selected_atom_data; $i++ ) {
    print( join( " ", @{ $selected_atom_data[$i] } ), "\n" );
}
