#!/usr/bin/perl

use strict;
use warnings;

use Math::Complex;

use lib "../../lib/perl";
use AlterMolecule;

use lib "../lib";
use Utils;

#
# Unit test: LinearAlgebra::switch_ref_frame.
#
# Changes frame of reference from global to local or vice versa.
#
# Example: ./switch_ref_frame "label_atom_id CA,N,CB,OG" \
#                             "Cartn_x,Cartn_y,Cartn_z" \
#                             "global" < example.cif
#

my $attribute_filter = shift;
my $attribute_select = shift;
my $ref_frame = shift;
my @cif = <>;

# Selects atom's data for further analysis.
my $selected_atom_data =
    Utils::select_atom_data( $attribute_filter,
			     $attribute_select,
			     @cif );

my @switched_ref_frame =
    LinearAlgebra::switch_ref_frame( $ref_frame,
				     $selected_atom_data->[1],
				     $selected_atom_data->[2],
				     $selected_atom_data->[0] );

foreach( @switched_ref_frame ) {
	foreach( @$_ ) {
	    print( join( "\t", @$_ ), "\n" );
	}
}
