#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;

use lib "../../lib/perl";
use LinearAlgebra;

my $symbols = shift;
my @symbols = [ split( ",", $symbols ) ];
my @symb_matrices = ( [] );

while( <> ) {
    if( $_ =~ /^\n$/ ) {
	push( @symb_matrices, [] );
    } else {
	push( @{ $symb_matrices[-1] }, [ split( " ", $_ ) ] );
    }
} 

LinearAlgebra::symb_dot_product( @symbols,
				 $symb_matrices[0],
				 $symb_matrices[1] );
