#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use LinearAlgebra;

my @matrix;

while( <> ) {
    push( @matrix, [ split( " ", $_ ) ] );
}

my $transposed_matrix =
    LinearAlgebra::transpose( \@matrix );

foreach( @$transposed_matrix ) {
    print( join( "\t", @$_ ), "\n" );
}
