#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use PDBxParser qw( obtain_atom_site
                   to_pdbx );
use PseudoAtoms qw( add_hydrogens );

use lib "../lib";
use Utils qw( select_atom_data );

my ( $pdbx_file ) = @ARGV;

my $atom_site = obtain_atom_site( $pdbx_file );

%{ $atom_site } =
    ( %{ $atom_site },
      %{ add_hydrogens( $atom_site ) } );

# Prints out PDBx format file.
to_pdbx( $atom_site );
