#!/usr/bin/perl

use strict;
use warnings;

use Math::Trig;

use lib "../../lib/perl";
use CifParser qw( filter_atoms
                  obtain_atom_site );
use LinearAlgebra qw( $PI );
use Measure qw( all_dihedral );

my ( $resi_specifier, $cif_file ) = @ARGV;

# Parses selector argument from string  to proper array.
my %resi_specifier = ( map { $_->[0] => [ split( ",", @$_[1] ) ] }
			  map { [ split( " ", $_ ) ] }
			  split( "&", $resi_specifier ) );

# Calculates all angles of given sidechains.
my $target_resi =
    filter_atoms( \%resi_specifier, obtain_atom_site( $cif_file ) );

# Calculates and prints out every dihedral angle for each residue.
my $dihedral_angles = all_dihedral( $target_resi );

for my $residue ( keys %{ $dihedral_angles } ) {
    for my $angle ( keys %{ $dihedral_angles->{$residue} } ) {
	print( $residue, "\t",
	       $angle, "\t",
	       $dihedral_angles->{$residue}{$angle} * 180 / $PI, "\n" );
    }
}
