#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use Measure qw( bond_length );

use lib "../lib";
use Utils qw( select_atom_data );

#
# Unit test: Measure::bond_length
#
# Measure the length of the bond between two atoms in angstroms.
#
# Example: ./bond_length "id 1,2" "Cartn_x,Cartn_y,Cartn_z" example.cif
#

my ( $attribute_filter, $attribute_select, $cif_file ) = @ARGV;

# Selects atom's data for further analysis.
my $selected_atom_data = select_atom_data( $attribute_filter,
					   $attribute_select,
					   $cif_file );

# Prints out length of the bond in angstroms.
printf( "%.3f\n", bond_length( @$selected_atom_data ) );
