#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use Measure qw( bond_angle );

use lib "../lib";
use Utils qw( select_atom_data );

#
# Unit test: Measure::bond_angle
#
# Measure the angle between three atoms in radians.
#
# Example: ./bond_angle "id 1,2,3" "Cartn_x,Cartn_y,Cartn_z" < example.cif
#

my $attribute_filter = shift;
my $attribute_select = shift;
my $angle = shift;
my @cif = <>;

# Selects atom's data for further analysis.
my $selected_atom_data = select_atom_data( $attribute_filter,
					   $attribute_select,
					   @cif );

# Prints out length of the bond in angstroms.
printf( "%.3f\n", bond_angle( $selected_atom_data ) );
