#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use CifParser qw( obtain_atom_site );
use ConnectAtoms qw( connect_atoms );

#
# Unit test: ConnectAtoms::connect_atoms
#
# Shows connections between atoms.
#
# Example: ./connect_atoms 1.51 0.15 < example.cif
#

#    In angstroms  In angstroms
my ( $bond_length, $bond_length_error, $cif ) = @ARGV;

# Selects atom's data for further analysis.
my $atom_site = obtain_atom_site( $cif );

# my %connected_atoms = %{
    connect_atoms( $atom_site ) # }
;

# my @atom_coord;
# my @parent_atom;
# my @child_atom;

# foreach( keys %{ $connected_atoms{"data"} } ) {
#     @parent_atom = ( $_, $connected_atoms{"data"}{$_}{"label_atom_id"} );
#     foreach( @{ $connected_atoms{"data"}{$_}{"connections"} } ) {
#         @child_atom = ( $_, $connected_atoms{"data"}{$_}{"label_atom_id"} );
#         print( "$parent_atom[0] $parent_atom[1]:" );
#         print( "$child_atom[0] $child_atom[1]\n" );
#     }
# }
