#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use LoadParams qw( covalent_radii );

@ARGV = ( "-" ) unless @ARGV;

foreach my $parameter_file ( @ARGV ) {
    covalent_radii( $parameter_file );
}
