#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use ConnectAtoms qw( create_box );

use lib "../lib";
use Utils qw( select_atom_data );

#
# Unit test: ConnectAtoms::create_box.
#
# Creates smallest possible box that surrounds all selected atoms.
#
# Example: ./create_box example.cif
#

my ( $atom_specifier, $pdbx_file ) = @ARGV;

# Selects atom's data for further analysis.
my $atom_data = select_atom_data( $pdbx_file,
				  $atom_specifier,
				  "Cartn_x,Cartn_y,Cartn_z" );

# Creates and prints out the boundaries of the box.
my $boundary_box = create_box( $atom_data );

print( "$boundary_box->[0]\t$boundary_box->[1]\n" .
       "$boundary_box->[2]\t$boundary_box->[3]\n" .
       "$boundary_box->[4]\t$boundary_box->[5]\n" );
