#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use ConnectAtoms qw( create_box );

use lib "../lib";
use Utils qw( select_atom_data );

#
# Unit test: ConnectAtoms::create_box.
#
# Creates smallest possible box that surrounds all selected atoms.
#
# Example: ./create_box < example.cif
#

my $attribute_selector = shift;
my @cif = <>;

# Selects atom's data for further analysis.
my $selected_atom_data = select_atom_data( $attribute_selector,
					   "Cartn_x,Cartn_y,Cartn_z",
					   @cif );

# Creates and prints out the boundaries of the box.
my @box_boundaries = create_box( @$selected_atom_data );

print( map { ( $_ % 2 ) == 0
		        ? $box_boundaries[$_-1] . "\n"
			: $box_boundaries[$_-1] . "\t" }
       ( 1..$#box_boundaries + 1 ) )
