#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use Measure;

use lib "../lib";
use Utils;

#
# Unit test: Measure::dihedral_angle
#
# Measure the dihedral angle of four atoms in radians.
#
# Example: ./dihedral_angle "id 1,2,3,4" "Cartn_x,Cartn_y,Cartn_z" < example.cif
#

my $attribute_filter = shift;
my $attribute_select = shift;
my $angle = shift;
my @cif = <>;

# Selects atom's data for further analysis.
my $selected_atom_data =
    Utils::select_atom_data( $attribute_filter,
			     $attribute_select,
			     @cif );

# Prints out length of the bond in angstroms.
printf( "%.3f\n", Measure::dihedral_angle( $selected_atom_data ) );
