#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use PDBxParser qw( filter_atoms obtain_atom_site to_pdbx );

#
# Unit test: CifParser::filter_atoms.
#
# Filters atoms by given attribute name and their values.
#
# Example: ./filter_atoms "label_comp_id SER & label_atom_id CA,N,CB,OG" \
#          example.cif
#

@ARGV = ( "-" ) unless @ARGV;

my ( $atom_specifier, $pdbx_file ) = @ARGV;

# Parses selector argument from string  to proper array.
my %atom_specifier = ( map { $_->[0] => [ split( ",", @$_[1] ) ] }
		       map { [ split( " ", $_ ) ] }
		       split( "&", $atom_specifier ) );

my $filtered_atoms = filter_atoms( obtain_atom_site( $pdbx_file ),
				   \%atom_specifier);
