#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use LinearAlgebra qw( pi );
use PDBxParser qw( obtain_atom_site );
use PseudoAtoms qw( generate_library );
use SidechainModels qw( rotation_only );

my ( $residue_id, $small_angle, $pdbx_file ) = @ARGV;

my $atom_site = obtain_atom_site( $pdbx_file );
$small_angle =~ s/pi/pi\(\)/g;

# In Jmol, generates pseudo-atoms which represent positions of atom
# after rotation along dihedral angle.
open( my $fh, "<", $pdbx_file );
chomp( my @pdbx_lines = <$fh> );
close( $fh );

# Creates pseudo-atoms for given analytical equation that describes conformation
# of atom.
%{ $atom_site } =
    ( %{ $atom_site },
      %{ generate_library( { "atom_site"     => $atom_site,
			     "residue_ids"   => [ $residue_id ],
			     "small_angle"   => eval( $small_angle ),
			     "conformations" => \&rotation_only,
			     "interactions"  => "hard_sphere",
			     "cutoff"        => 0  } ) } );

# Prints out count of atoms and arbitrary word that are neccessary for Jmol.
print( scalar( keys %{ $atom_site } ), "\n" );
print( "testing\n" );

# Prints out pseudo-atom coordinates.
for my $atom_id ( sort { $a <=> $b } keys %{ $atom_site } ) {
    printf( "$atom_site->{$atom_id}{\"type_symbol\"}" .
	    "\t%.3f\t%.3f\t%.3f\n",
	    $atom_site->{$atom_id}{"Cartn_x"},
	    $atom_site->{$atom_id}{"Cartn_y"},
	    $atom_site->{$atom_id}{"Cartn_z"} );
}
