#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use AtomClashes qw( radius_only );
use PDBxParser qw( obtain_atom_site );
use PseudoAtoms qw( generate_library );
use SidechainModels qw( rotation_only );

my ( $residue_id, $pdbx_file ) = @ARGV;

# Selects atom's data for further analysis.
my $atom_site = obtain_atom_site( $pdbx_file );

# Parses angles for pseudo-rotamers.
generate_library( { "atom_site"    => $atom_site,
		    "residue_ids"  => [ $residue_id ],
		    "movements"    => \&rotation_only,
		    "interactions" => \&radius_only } );
