#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use LinearAlgebra;

use Data::Dumper;

#
# Unit test: LinearAlgebra::matrix_sum.
#
# Adds two matrices.
#
# Example: ./matrix_sum < example.dat
#

my @matrices = ( [] );

while( <> ) {
    if( $_ =~ /^\n$/ ) {
	push( @matrices, [] );
    } else {
	push( @{ $matrices[-1] }, [ split( " ", $_ ) ] );
    }
}

my @left_matrix = @{ $matrices[0] };
my @right_matrix = @{ $matrices[1] };

my $matrix_sum =
    LinearAlgebra::matrix_sum( \@left_matrix, \@right_matrix );

foreach( @$matrix_sum ) {
    print( join( "\t", @$_ ), "\n" );
}
