#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use PDBxParser qw( obtain_atom_site to_pdbx );

#
# Unit test: PDBxParser::obtain_atom_site
#
# Creates standard PDBx output with only _atom_site category and checks if all
# data was correctly obtained.
#
# Example: ./obtain_atom_site example.cif
#

@ARGV = ( "-" ) unless @ARGV;

my $atom_site;

foreach my $pdbx_file ( @ARGV ) {
    $atom_site = obtain_atom_site( $pdbx_file );

    to_pdbx( $atom_site );
}
