#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use Measure qw( rmsd );

use lib "../lib";
use Utils;

#
# Unit test: Measure::rmsd
#
# Measure root-mean-square deviation of two same-length sets.
#
# Example: ./dihedral_angle example_set.cif
#

my ( $cif_file ) = @ARGV;
my @coord_sets = ( [] );

open( my $fh, "<", $cif_file );
while( <$fh> ) {
    if( $_ =~ /^\n$/ ) {
	push( @coord_sets, [] );
    } else {
	push( @{ $coord_sets[-1] }, [ split( " ", $_ ) ] );
    }
}
close( $fh );

# Prints out rmsd of given two sets.
printf( "%.3f\n", rmsd( @coord_sets ) );
