#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use SidechainModels;

use lib "../lib";
use Utils;

use Data::Dumper;

my $attribute_filter = shift;
my @cif = <>;

my $selected_atom_data =
    CifParser::select_atom_data( [],
				 [ "id",
                                   "label_atom_id",
                                   "label_comp_id",
                                   "Cartn_x",
                                   "Cartn_y",
                                   "Cartn_z" ],
				 @cif );

# Applies molecule alterations.
SidechainModels::rotation_only( @$selected_atom_data );
