#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use LinearAlgebra;

use lib "../lib";
use Utils;

#
# Unit test: LinearAlgebra::rotate_z_axis.
#
# Rotates along z-axis of the global frame of reference.
#
# Example: ./rotate_z_axis "label_atom_id CA,N,CB,OG" \
#                          "Cartn_x,Cartn_y,Cartn_z" \
#                          "1.571" < example.cif
#

my $attribute_filter = shift;
my $attribute_select = shift;
my $angle = shift;
my @cif = <>;

# Selects atom's data for further analysis.
my $selected_atom_data =
    Utils::select_atom_data( $attribute_filter,
			     $attribute_select,
			     @cif );

# Rotates all atoms along z-axis by given angle.
my @transf_atom_data;

foreach ( @$selected_atom_data ) {
    # Prepared atom coordinates to proper 4x1 matrix.
    my @atom_coord;

    foreach( @$_ ) {
	push( @atom_coord, [ $_ ] );
    }

    push( @atom_coord, [ 1 ] );

    # Makes actual rotation.
    push( @transf_atom_data,
	  LinearAlgebra::two_matrix_product(
	      [ "i" ],
	      LinearAlgebra::rotate_z_axis( $angle ),
	      \@atom_coord ) );
}

# Prints out results.
map { printf( "%.3f\t%.3f\t%.3f\n",
	      $_->[0][0],
	      $_->[1][0],
	      $_->[2][0] ) }
@transf_atom_data;
