#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use Sampling qw( sample_angles );
use Data::Dumper;
#
# Unit test: Sampling::sample_angles
#
# Samples angles according to angle range and size of increment.
#
# Example: ./sample_angles "0-1,3-4" 0.5
#

my ( $angle_ranges, $angle_df ) = @ARGV;

my @angle_ranges = ( map { [ $_->[0],  $_->[1] ] }
		     map { [ split( "-", $_ ) ] }
		     split( ",", $angle_ranges ) );

my $sample_angles = sample_angles(  \@angle_ranges, $angle_df );

for my $angle ( @{ $sample_angles } ) {
    printf( "%.2f\n", $angle );
}
