#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use CifParser;

#
# Unit test: CifParser::select_atom_data.
#
# Selects atom data by given attributes.
#
# Example: ./select_atom_data "label_atom_id CA,N,CB,OG" \
#                             "Cartn_x,Cartn_y,Cartn_z" < example.cif
#

my $attribute_selector = shift;
my $data_selector = shift;

# Parses selector argument from string  to proper array.
my %attribute_selector = ( map { $_->[0] => [ split( ",", @$_[1] ) ] }
                           map { [ split( " ", $_ ) ] }
                           split( "&", $attribute_selector ) );
my @data_selector = split( ",", $data_selector );

# Selects atoms for further analysis.
my @selected_atom_data =
    @{ CifParser::select_atom_data(
	   \@data_selector,
	   &CifParser::filter_atoms(
	       \%attribute_selector,
	       &CifParser::obtain_atom_site( <> ) ) ) };

for( my $i = 0; $i <= $#selected_atom_data; $i++ ) {
    print( join( " ", @{ $selected_atom_data[$i] } ), "\n" );
}
