#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use PDBxParser qw( filter_atoms select_atom_data obtain_atom_site to_pdbx );

#
# Unit test: PDBxParser::select_atom_data.
#
# Selects atom data by given attributes.
#
# Example: ./select_atom_data "label_atom_id CA,N,CB,OG" \
#                             "Cartn_x,Cartn_y,Cartn_z" example.cif
#

@ARGV = ( "-" ) unless @ARGV;
my ( $atom_specifier, $data_specifier, $pdbx_file ) = @ARGV;

my %atom_specifier = ( map { $_->[0] => [ split( ",", @$_[1] ) ] }
		       map { [ split( " ", $_ ) ] }
		       split( "&", $atom_specifier ) );
my @data_specifier = split( ",", $data_specifier );

my @atom_data =
    @{ select_atom_data( filter_atoms( obtain_atom_site( $pdbx_file ),
				       \%atom_specifier ),
			 \@data_specifier ) };

for( my $i = 0; $i <= $#atom_data; $i++ ) {
    print( join( " ", @{ $atom_data[$i] } ), "\n" );
}
