#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use CifParser qw( select_atom_data
                  filter_atoms
                  obtain_atom_site );

#
# Unit test: CifParser::select_atom_data.
#
# Selects atom data by given attributes.
#
# Example: ./select_atom_data "label_atom_id CA,N,CB,OG" \
#                             "Cartn_x,Cartn_y,Cartn_z" < example.cif
#

@ARGV = ( "-" ) unless @ARGV;
my ( $attribute_selector, $data_selector, $cif_file ) = @ARGV;

# Parses selector argument from string  to proper array.
my %attribute_selector = ( map { $_->[0] => [ split( ",", @$_[1] ) ] }
                           map { [ split( " ", $_ ) ] }
                           split( "&", $attribute_selector ) );

my @data_selector = split( ",", $data_selector );

# Selects atoms for further analysis.
my @selected_atom_data =
    @{ select_atom_data( \@data_selector,
			 &filter_atoms( \%attribute_selector,
					&obtain_atom_site( $cif_file ) ) ) };

for( my $i = 0; $i <= $#selected_atom_data; $i++ ) {
    print( join( " ", @{ $selected_atom_data[$i] } ), "\n" );
}
