#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib";
use ConnectAtoms qw( sort_by_priority );

#
# Unit test: ConnectAtoms::sort_by_priority.
#
# Example: ./sort_by_priority atom_names.dat
#

my ( $atom_names_file ) = @ARGV;

open( my $fh, "<", $atom_names_file );
my @atom_names = <$fh>;
close( $fh );

my ( $atom_names ) =
    map { [ split( " ", $_ ) ] } grep { $_ ne "\n" } @atom_names;

my $sorted_names = sort_by_priority( $atom_names );

print( join( " ", @{ $sorted_names } ), "\n" );
