#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use LinearAlgebra qw( switch_ref_frame );

use lib "../lib";
use Utils qw( select_atom_data );
use Data::Dumper;
#
# Unit test: LinearAlgebra::switch_ref_frame.
#
# Changes frame of reference from global to local or vice versa.
#
# Example: ./switch_ref_frame "label_atom_id CA,N,CB,OG" \
#                             "Cartn_x,Cartn_y,Cartn_z" \
#                             "global" example.cif
#

my ( $atom_specifier, $data_specifier, $ref_frame, $pdbx_file ) = @ARGV;

# Selects atom's data for further analysis.
my $atom_data = 
    select_atom_data( $pdbx_file,
		      $atom_specifier,
		      $data_specifier );

my $ref_frame_coord = 
    switch_ref_frame( $atom_data->[1],
		      $atom_data->[2],
		      $atom_data->[0],
		      $ref_frame );

for my $row ( @{ $ref_frame_coord } ) {
    print( join( "\t", @{ $row } ), "\n" );
}
