#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use LinearAlgebra qw( switch_ref_frame );

use lib "../lib";
use Utils qw( select_atom_data );

#
# Unit test: LinearAlgebra::switch_ref_frame.
#
# Changes frame of reference from global to local or vice versa.
#
# Example: ./switch_ref_frame "label_atom_id CA,N,CB,OG" \
#                             "Cartn_x,Cartn_y,Cartn_z" \
#                             "global" < example.cif
#

my $attribute_filter = shift;
my $attribute_select = shift;
my $ref_frame = shift;
my @cif = <>;

# Selects atom's data for further analysis.
my $selected_atom_data = select_atom_data( $attribute_filter,
					   $attribute_select,
					   @cif );

my @switched_ref_frame = switch_ref_frame( $ref_frame,
					   $selected_atom_data->[1],
					   $selected_atom_data->[2],
					   $selected_atom_data->[0] );

foreach( @switched_ref_frame ) {
	foreach( @$_ ) {
	    print( join( "\t", @$_ ), "\n" );
	}
}
