#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use LinearAlgebra qw( transpose );

#
# Unit test: LinearAlgebra::transpose
#
# Transposes matrix.
#
# Example: ./transpose example.dat
#

@ARGV = ( "-" ) unless @ARGV;
my ( $cif_file ) = @ARGV;

my @matrix;

open( my $fh, "<", $cif_file );
while( <$fh> ) {
    push( @matrix, [ split( " ", $_ ) ] );
}
close( $fh );

my $transposed_matrix = transpose( \@matrix );

foreach( @$transposed_matrix ) {
    print( join( "\t", @$_ ), "\n" );
}
