#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use LinearAlgebra qw( matrix_product translation );

use lib "../lib";
use Utils qw( select_atom_data );

#
# Unit test: LinearAlgebra::translation.
#
# Translates atom by a given displacement.
#
# Example: ./translation "label_atom_id CA,N,CB,OG" "Cartn_x,Cartn_y,Cartn_z" \
#                        "1.000,1.000,1.000" example.cif
#

my ( $atom_specifier, $data_specifier, $transl_coord, $pdbx_file ) = @ARGV;

my $atom_data = select_atom_data( $pdbx_file,
				  $atom_specifier,
				  $data_specifier );

# Translates coordinates by given displacement.
my @transl_coord = split( ",", $transl_coord );
my @transf_atom_data;

foreach ( @$selected_atom_data ) {
    # Prepared atom coordinates to proper 4x1 matrix.
    my @atom_coord;

    foreach( @$_ ) {
	push( @atom_coord, [ $_ ] );
    }

    push( @atom_coord, [ 1 ] );

    # Makes actual rotation.
    push( @transf_atom_data,
	  matrix_product(
	      translation( @transl_coord ),
	      \@atom_coord ) );
}

# Prints out results.
map { printf( "%.3f\t%.3f\t%.3f\n",
	      $_->[0][0],
	      $_->[1][0],
	      $_->[2][0] ) }
@transf_atom_data;
