#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use LinearAlgebra qw( matrix_product translation );

use lib "../lib";
use Utils qw( select_atom_data );

#
# Unit test: LinearAlgebra::translation.
#
# Translates atom by a given displacement.
#
# Example: ./translation "label_atom_id CA,N,CB,OG" "Cartn_x,Cartn_y,Cartn_z" \
#                        "1.000,1.000,1.000" example.cif
#

my ( $atom_specifier, $data_specifier, $transl_coord, $pdbx_file ) = @ARGV;

my $atom_data = select_atom_data( $pdbx_file,
				  $atom_specifier,
				  $data_specifier );
my @transl_coord = split( ",", $transl_coord );

# Translates coordinates by given displacement.
my $transf_atom_coord;

for my $atom_coord ( @{ $atom_data } ) {
    $transf_atom_coord =
	matrix_product( translation( @transl_coord ),
			[ [ $atom_coord->[0] ],
			  [ $atom_coord->[1] ],
			  [ $atom_coord->[2] ],
			  [ 1 ] ] );
    printf( "%.3f\t%.3f\t%.3f\n",
	    $transf_atom_coord->[0][0],
	    $transf_atom_coord->[1][0],
	    $transf_atom_coord->[2][0] );
}

