#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use LinearAlgebra qw( transpose );

#
# Unit test: LinearAlgebra::transpose
#
# Transposes matrix.
#
# Example: ./transpose < example.dat
#

my @matrix;

while( <> ) {
    push( @matrix, [ split( " ", $_ ) ] );
}

my $transposed_matrix = transpose( \@matrix );

foreach( @$transposed_matrix ) {
    print( join( "\t", @$_ ), "\n" );
}
