#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use LinearAlgebra;

#
# Unit test: LinearAlgebra::mult_matrix_product.
#
# Multiplies two matrices using symbolic algebra.
#
# Example: ./two_matrix_product "x,y,z" < example.dat
#

my $symbols = shift;
   $symbols //= ",";
my @symbols = [ split( ",", $symbols ) ];

my @symb_matrices = ( [] );

while( <> ) {
    if( $_ =~ /^\n$/ ) {
	push( @symb_matrices, [] );
    } else {
	push( @{ $symb_matrices[-1] }, [ split( " ", $_ ) ] );
    }
}

my $symb_dot_product =
    LinearAlgebra::two_matrix_product( @symbols,
				       $symb_matrices[0],
				       $symb_matrices[1] );

foreach( @$symb_dot_product ) {
    print( join( "\t", @$_ ), "\n" );
}
