#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib";
use LinearAlgebra qw( vector_cross );

#
# Unit test: LinearAlgebra::vector_cross.
#
# Calculates cross product of two 3D vectors.
#
# Example: ./vector_cross example.dat
#

my ( $vector_file ) = @ARGV;

open( my $fh, "<", $vector_file );
my @vector = <$fh>;
close( $fh );

my ( $left_matrix, $right_matrix ) =
    map { [ split( " ", $_ ) ] } grep { $_ ne "\n" } @vector;

my $cross_product = vector_cross( $left_matrix, $right_matrix );

print( join( "\t", @{ $cross_product } ), "\n" );
