#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use LinearAlgebra qw( vector_cross );

#
# Unit test: LinearAlgebra::vector_cross.
#
# Calculates cross product of two 3D vectors.
#
# Example: ./vector_cross < example.dat
#

my ( $left_matrix, $right_matrix ) =
    map { [ split( " ", $_ ) ] } grep { $_ ne "\n" } <>;

my $cross_product = vector_cross( $left_matrix, $right_matrix );

print( join( "\t", @$cross_product ) );
