#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use LinearAlgebra qw( matrix_product y_axis_rotation );

use lib "../lib";
use Utils qw( select_atom_data );

#
# Unit test: LinearAlgebra::y_axis_rotation.
#
# Rotates along y-axis of the global frame of reference.
#
# Example: ./y_axis_rotation "label_atom_id CA,N,CB,OG" \
#                            "Cartn_x,Cartn_y,Cartn_z" \
#                            "1.571" example.cif
#

my ( $atom_specifier, $data_specifier, $angle, $pdbx_file ) = @ARGV;

my $atom_data = select_atom_data( $pdbx_file,
				  $atom_specifier,
				  $data_specifier );

# Rotates all atoms along y-axis by given angle.
my @transf_atom_data;

foreach ( @$selected_atom_data ) {
    # Prepared atom coordinates to proper 4x1 matrix.
    my @atom_coord;

    foreach( @$_ ) {
	push( @atom_coord, [ $_ ] );
    }

    push( @atom_coord, [ 1 ] );

    # Makes actual rotation.
    push( @transf_atom_data,
	  matrix_product(
	      y_axis_rotation( $angle ),
	      \@atom_coord ) );
}

# Prints out results.
map { printf( "%.3f\t%.3f\t%.3f\n",
	      $_->[0][0],
	      $_->[1][0],
	      $_->[2][0] ) }
@transf_atom_data;
