#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib/perl";
use LinearAlgebra qw( matrix_product y_axis_rotation );

use lib "../lib";
use Utils qw( select_atom_data );

#
# Unit test: LinearAlgebra::y_axis_rotation.
#
# Rotates along y-axis of the global frame of reference.
#
# Example: ./y_axis_rotation "label_atom_id CA,N,CB,OG" \
#                            "Cartn_x,Cartn_y,Cartn_z" \
#                            "1.571" example.cif
#

my ( $atom_specifier, $data_specifier, $angle, $pdbx_file ) = @ARGV;

my $atom_data = select_atom_data( $pdbx_file,
				  $atom_specifier,
				  $data_specifier );

# Rotates all atoms along y-axis by given angle.
my $transf_atom_coord;

for my $atom_coord ( @{ $atom_data } ) {
    $transf_atom_coord =
	matrix_product( y_axis_rotation( $angle ),
			[ [ $atom_coord->[0] ],
			  [ $atom_coord->[1] ],
			  [ $atom_coord->[2] ],
			  [ 1 ] ] );
    printf( "%.3f\t%.3f\t%.3f\n",
	    $transf_atom_coord->[0][0],
	    $transf_atom_coord->[1][0],
	    $transf_atom_coord->[2][0] );
}
