#!/usr/bin/perl

use strict;
use warnings;

use Getopt::Long;
use FindBin;

use lib "$FindBin::Bin/../lib";
use PDBxParser qw( obtain_atom_site );

#*generate-rotamer
#*    generates rotamer library.
#*
#*USAGE:
#*    generate ...
#*
#*OPTIONS:
#*    -i, --input, <STDIN>
#*        PDBx file.
#*    -h, --help
#*        prints out help message.

# --------------------------------- Options ----------------------------------- #

my $pdbx_file;
my $help = 0;

GetOptions( "input=s" => \$pdbx_file,
	    "help" => sub { open( my $fh, "<", $0 );
			    while( <$fh> ) {
				my ( $help_message ) = $_ =~ m/^#(\*.*)/;
				$help_message =~ s/^\*$/ /g if $help_message;
				$help_message =~ s/^\*//g if $help_message;
				print( $help_message, "\n" ) if $help_message; }
			    close( $fh ) } )
or die "Error in command line argument.";

# ----------------------------------- Main ------------------------------------ #

my $atom_site;
if( -t STDIN ) {
    $atom_site = obtain_atom_site( $pdbx_file );
} else {
    $atom_site = obtain_atom_site(); # Reads STDIN.
}
