#!/usr/bin/perl
use strict;
use warnings;

use autodie;
use Clone qw( clone );
use Getopt::Long;
use JSON;
use List::Util qw( any
                   max
                   uniq );
use Try::Tiny;

use BondParameters qw( bendable_angles
                       collect_bond_parameters
                       collect_dihedral_angles
                       detect_bond_parameter_type
                       stretchable_bonds
                       rotatable_bonds );
use BondProperties qw( hybridization );
use ConnectAtoms qw( assign_hetatoms
                     connect_atoms
                     connections_from_struct_conn
                     struct_conn_atom_ids
                     struct_conn_from_connections
                     struct_conn_residue_keys );
use DBScan;
use ForceField::Parameters();
use Hydrogens qw( add_hydrogens );
use Logging qw( error
                warning );
use PDBxParser qw( change_unique_residue_key
                   extract
                   filter
                   filter_new
                   filter_by_unique_residue_key
                   increase_chain_id
                   mark_selection
                   obtain_pdbx_data
                   raw2indexed
                   split_by
                   to_pdbx
                   unique_residue_key );
use PseudoAtoms qw( generate_pseudo );
use SidechainModels qw( rotation_translation  );
use Version qw( $VERSION );

Getopt::Long::Configure qw( gnu_getopt );

our $VERSION = $VERSION;

#*rotag_add [options] (--side-chains | --hydrogens) [--] <cif-file>...
#*    add pseudo atoms.
#*
#*Usage:
#*    rotag_add --side-chains input.cif > output.cif
#*    rotag_add --hydrogens input.cif > output.cif
#*
#*Options:
#*    -S, --side-chains
#*                        add atoms of defined rotamer. Input .cif has to
#*                        contain _[local]_rotamer_angle category (can be
#*                        produced with rotag_library).
#*    -H, --hydrogens
#*                        add hydrogen atoms to selected atoms.
#*    -l, --ligands
#*                        add specified ligand.
#*    --list-ligands
#*                        list available ligands that can be added.
#*    --optimise-ligands
#*                        clusters ligands using DBScan algorithm, reduces
#*                        possible positions and checks the ligand coordination.
#*    --dbscan-distance
#*                        maximum dinstance between atoms that includes
#*                        them to the cluster. Works only when
#*                        "--optimise-ligands" option is on.
#*    --dbscan-min
#*                        minimum atom neighbour count for the points to be
#*                        considered included in the cluster. Works only when
#*                        "--optimise-ligands" option is on.
#*    -a, --rotamer-angle-file
#*                        selects rotamer angles from the cif file.
#*    -j, --rotamer-angle-json-file
#*                        selects rotamer angles from the json file.
#*    -s, --selected
#*                        include selected atoms.
#*    --tags <tag>[,<tag>...]
#*                        select PDBx category that will be in the output.
#*                        (default: "_atom_site").
#*    -k, --keep-original
#*                        keep original atoms after new atoms are added
#*                        (applicable only for --side-chains option).
#*    -c, --clear-positions
#*                        add only those hydrogens that have clear positions from
#*                        the current structure (applicable for --hydrogens
#*                        option).
#*    -b, --b-factor
#*                        adds 'B_iso_or_equiv' as energy value to the PDBx
#*                        'atom_site' loop.
#*    -v, --version
#*                        print version.

# --------------------------------- Options ----------------------------------- #

my $add_sidechains = 0;
my $add_hydrogens = 0;
my $ligands = '';
my $list_ligands = 0;
my $optimise_ligands = 0;
my $dbscan_distance = 1.0;
my $dbscan_min = 1;
my $rotamer_angle_file = '';
my $rotamer_angle_json_file = '';
my $include_selected = 0;
my $tags = '_atom_site';
my $add_clear_positions = 0;
my $keep_original = 0;
my $add_B_iso = 0;
my @category_list =
    ( '_atom_site', '_[local]_rotamer_energy', '_[local]_rotamer_bond_parameter',
      '_struct_conn' );

local $SIG{__WARN__} = sub {
    warning( { 'program' => $0,
               'message' => @_,
               'filename' => join( ', ', @ARGV ) } );
};

local $SIG{__DIE__} = sub {
    error( { 'program' => $0,
             'message' => @_,
             'filename' => join( ', ', @ARGV ) } );
};

GetOptions(
    'side-chains|S' => sub { $add_sidechains = 1 },
    'hydrogens|H' => sub { $add_hydrogens = 1 },
    'l|ligands=s' => \$ligands,
    'list-ligands' => sub { $list_ligands = 1 },
    'optimise-ligands' => sub { $optimise_ligands = 1 },
    'dbscan-distance=s' => \$dbscan_distance,
    'dbscan-min=s' => \$dbscan_min,
    'a|rotamer-angle-cif-file=s' => \$rotamer_angle_file,
    'j|rotamer-angle-json-file=s' => \$rotamer_angle_json_file,
    'selected|s' => sub { $include_selected = 1 },
    'tags=s' => \$tags,
    'keep-original|k' => sub { $keep_original = 1 },
    'clear-positions|c' => sub { $add_clear_positions = 1 },
    'b-factor|b' => sub { $add_B_iso = 1;
                          push @category_list, '_[local]_rotamer_energy' },
    'help|h' => sub {
                        open my $fh, '<', $0;
                        while( <$fh> ) {
                            my ( $help_message ) = $_ =~ m/^#(\*.*)/;
                            if( $help_message ) {
                                $help_message =~ s/^\*$/ /smgx;
                                $help_message =~ s/^\*//smgx;
                                print $help_message, "\n";
                            }
                        }
                        close $fh;
                        exit;
                    },
    'version|v' => sub { print $VERSION, "\n"; exit; }
) or error( { 'program' => $0,
              'message' => "mistake in command line argument.\n" } );

# ----------------------------------- Main ------------------------------------ #

local @ARGV = ( q{-} ) unless @ARGV;

$tags =~ s/ //g;
my @tags = split /,/, $tags;

my $parameters = Parameters->new();
my $pi = $parameters->{'_[local]_constants'}{'pi'};
my $interaction_atom_names = $parameters->{'_[local]_interaction_atom_names'};
my $moieties = $parameters->{'_[local]_moieties'};
my $heteroatom_extension = $parameters->{'_[local]_sidechain_hetatom_extension'};

if( $list_ligands ) {
    map { print $_, "\n" }
    sort
    keys %{ $parameters->{'_[local]_sidechain_hetatom_extension'} };
    exit;
}

my @add_ligands = grep { $_ ne '' } split /,/, $ligands;

# NOTE: the whole script needs thorough refactoring.
# TODO: rename rotamer angle to rotamer bond parameters.
# TODO: keep '_[local]_rotamer_angle'.
for my $pdbx_file ( @ARGV ) {
    my $pdbx = obtain_pdbx_data( $pdbx_file, \@category_list );
    raw2indexed( $pdbx,
                 { 'attributes' => { '_atom_site' => [ 'id' ],
                                     '_[local]_rotamer_bond_parameter' =>
                                         [ 'id' ],
                                     '_struct_conn' => [ 'id' ],
                                     ( $add_B_iso || $optimise_ligands ?
                                       ( '_[local]_rotamer_energy' =>
                                             [ 'rotamer_id' ] ) : () ) } } );

    # Reads file path, stdin and '-' operator.
    my $atom_site = $pdbx->{'_atom_site'}{'data'};
    my $struct_conn = $pdbx->{'_struct_conn'}{'data'};

    if( ! defined $atom_site ) {
        warning( { 'program' => $0,
                   'message' => "no atom sites were detected.\n" } );
        next;
    }

    my $selected_atom_site =
        filter( { 'atom_site' => $atom_site,
                  'include' => { '[local]_selection_state' =>
                                     [ 'T', 'S' ] } } );

    # Selects all atoms if no specific atoms are selected.
    if( ! %{ $selected_atom_site } ) {
        $selected_atom_site = $atom_site;
        mark_selection( $atom_site,
                        { 'target' => [ keys %{ $selected_atom_site } ] } );
    }

    my $target_atom_site =
        filter( { 'atom_site' => $selected_atom_site,
                  'include' => { '[local]_selection_state' =>
                                 ( $include_selected ?
                                   [ 'T', 'S' ] : [ 'T' ] ) } } );

    my %exclude_atom_names = map { $_ => 1 } @{ $interaction_atom_names };

    # # TODO: seek for refactoring as it is a bit messy.
    # my $target_atom_site_only =
    #     filter( { 'atom_site' => $target_atom_site,
    #               'include' => { '[local]_selection_state' => [ 'T' ] },
    #               'exclude' => { 'label_atom_id' =>
    #                                  $interaction_atom_names } } );

    my $rotamer_angle_data_json;
    if( $rotamer_angle_json_file ) {
        my $json;
        {
            local $/; #Enable 'slurp' mode
            open my $fh, "<", $rotamer_angle_json_file;
            $json = <$fh>;
            close $fh;
        }
        $rotamer_angle_data_json = decode_json( $json );
    }

    if( $add_sidechains ) {
        my $rotamer_angle;
        my $rotamer_energy;
        if( defined $rotamer_angle_data_json ) {
            # NOTE: should be changed to rotamer_bond_parameter.
            $rotamer_angle = $rotamer_angle_data_json->{'rotamer_angle'};
        } elsif( $rotamer_angle_file  ) {
            my $pdbx_rotamer_angle =
                obtain_pdbx_data( $rotamer_angle_file,
                                  [ '_[local]_rotamer_bond_parameter' ] );
            raw2indexed( $pdbx_rotamer_angle,
                         { 'attributes' =>
                               { '_[local]_rotamer_bond_parameter' =>
                                     [ 'id' ] } } );
            $rotamer_angle =
                $pdbx_rotamer_angle->{'_[local]_rotamer_bond_parameter'}{'data'};
        } else {
            $rotamer_angle = $pdbx->{'_[local]_rotamer_bond_parameter'}{'data'};
        }

        if( $add_B_iso || $optimise_ligands ) {
            $rotamer_energy = $pdbx->{'_[local]_rotamer_energy'}{'data'};
        }

        if( ! defined $rotamer_angle ) {
            warning( { 'program' => $0,
                       'message' => "no rotamer angles were detected.\n" } );
            next;
        }

        # Determines, how to split rotamer angles into groups.
        my $rotamer_angle_split_groups = {};
        my @rotamer_ids = sort keys %{ $rotamer_angle };
        if( defined $rotamer_angle_data_json ) {
            $rotamer_angle_split_groups =
                $rotamer_angle_data_json->{'rotamer_angle_grouped'};
        } elsif( ( exists $rotamer_angle->{$rotamer_ids[0]}{'label_seq_id'} &&
                   exists $rotamer_angle->{$rotamer_ids[0]}{'label_asym_id'} &&
                   exists $rotamer_angle->{$rotamer_ids[0]}{'label_alt_id'} &&
                   exists $rotamer_angle->{$rotamer_ids[0]}{'pdbx_PDB_model_num'} ) ||
                 ( exists $rotamer_angle->{$rotamer_ids[0]}{'auth_seq_id'} &&
                   exists $rotamer_angle->{$rotamer_ids[0]}{'auth_asym_id'} &&
                   exists $rotamer_angle->{$rotamer_ids[0]}{'label_alt_id'} &&
                   exists $rotamer_angle->{$rotamer_ids[0]}{'pdbx_PDB_model_num'} ) ) {
            # TODO: 'atom_site' should be changed to 'loop_site' in the future.
            # TODO: also check if 'pdbx_auth_alt_id' should not be added.
            $rotamer_angle_split_groups =
                split_by( { 'atom_site' => $rotamer_angle,
                            'attributes' => [
                                'label_seq_id',
                                'label_asym_id',
                                'pdbx_PDB_model_num',
                                'label_alt_id',
                                'auth_seq_id',
                                'auth_asym_id',
                                'pdbx_auth_alt_id'
                            ] } );
        } elsif( exists $rotamer_angle->{$rotamer_ids[0]}{'phi_min'} &&
                 exists $rotamer_angle->{$rotamer_ids[0]}{'phi_max'} &&
                 exists $rotamer_angle->{$rotamer_ids[0]}{'psi_min'} &&
                 exists $rotamer_angle->{$rotamer_ids[0]}{'psi_max'} ) {
            $rotamer_angle_split_groups =
                split_by( { 'atom_site' => $rotamer_angle,
                            'attributes' => [ 'label_comp_id',
                                              'phi_min',
                                              'psi_min' ] } );
        } elsif( exists $rotamer_angle->{$rotamer_ids[0]}{'phi'} &&
                 exists $rotamer_angle->{$rotamer_ids[0]}{'psi'} ) {
            $rotamer_angle_split_groups =
                # TODO: 'atom_site' should be changed to 'loop_site' in the
                # future.
                split_by( { 'atom_site' => $rotamer_angle,
                            'attributes' => [ 'label_comp_id',
                                              'phi',
                                              'psi' ] } );
        } elsif( exists $rotamer_angle->{$rotamer_ids[0]}{'label_comp_id'} ) {
            $rotamer_angle_split_groups =
                # TODO: 'atom_site' should be changed to 'loop_site' in the
                # future.
                split_by( { 'atom_site' => $rotamer_angle,
                            'attributes' => [ 'label_comp_id' ] } );
        }

        my $struct_conn_connections =
            connections_from_struct_conn( $target_atom_site, $struct_conn );

        # Maps bond parameter ids to rotamer ids bidirectionally.
        my %bond_parameter_to_rotamer_tbl = ();
        my %rotamer_to_bond_parameter_tbl = ();
        for my $bond_parameter_id ( keys %{ $rotamer_angle } ) {
            my $rotamer_id = $rotamer_angle->{$bond_parameter_id}{'rotamer_id'};
            $bond_parameter_to_rotamer_tbl{$bond_parameter_id} = $rotamer_id;
            $rotamer_to_bond_parameter_tbl{$rotamer_id}{$bond_parameter_id} = 1;
        }

        my @bond_parameter_types =
            map { [ detect_bond_parameter_type( $_ ) ] }
            uniq sort
            map { $rotamer_angle->{$_}{'type'} }
            keys %{ $rotamer_angle };

        my $include_hetatoms =
            any { $_->[1] } @bond_parameter_types;
        my $do_rotable_bonds =
            any { $_->[0] eq 'dihedral_angle' } @bond_parameter_types;
        my $do_stretchable_bonds =
            any { $_->[0] eq 'bond_length' } @bond_parameter_types;
        my $do_bendable_angles =
            any { $_->[0] eq 'bond_angle' } @bond_parameter_types;

        my %rotamer_atom_site;
        my %tracked_auth_alt_ids = ();
        my %delete_original = ();
        my $last_atom_id = max( keys %{ $atom_site } );
        for my $residue_unique_key ( sort keys %{ $rotamer_angle_split_groups } ) {
            my $residue_site = filter_by_unique_residue_key(
                $target_atom_site,
                $residue_unique_key,
                1
            );

            # Rotamer can only be started from ATOM. Otherwise, HETATM
            # searches for connections until ATOM is found.
            my ( $label_seq_id ) = split /,/, $residue_unique_key;
            if( $label_seq_id eq '.' ) {
                my @related_residue_unique_keys =
                    uniq sort
                    map { unique_residue_key( $target_atom_site->{$_} ) }
                    grep { $target_atom_site->{$_}{'group_PDB'} eq 'ATOM'  }
                    map { keys %{ $struct_conn_connections->{$_} } }
                    keys %{ $residue_site };

                next if ! @related_residue_unique_keys;

                my $old_residue_unique_key = $residue_unique_key;

                ( $residue_unique_key ) = @related_residue_unique_keys;

                $residue_site = filter_by_unique_residue_key(
                    $target_atom_site,
                    $residue_unique_key,
                    1
                );

                # $rotamer_angle_split_groups->{$residue_unique_key} =
                #     clone $rotamer_angle_split_groups->{$old_residue_unique_key};

                # delete $rotamer_angle_split_groups->{$old_residue_unique_key};

                # $label_seq_id = split /,/, $residue_unique_key;
            }

            next if $label_seq_id eq '.';

            # TODO: check if the overwriting the global variable is not
            # dangerous.
            my $additional_struct_conn =
                struct_conn_from_connections( $parameters,
                                              $residue_site,
                                              $struct_conn );
            $struct_conn = {
                ( defined $struct_conn ? %{ $struct_conn } : () ),
                %{ $additional_struct_conn }
            };

            my $struct_conn_atom_ids =
                struct_conn_atom_ids( $residue_site, $struct_conn );

            if( @{ $struct_conn_atom_ids } ) {
                my $assigned_hetatom_ids =
                    assign_hetatoms( $parameters,
                                     $residue_site,
                                     $struct_conn,
                                     { 'sidechains_only' => 1,
                                       'ref_atom_site' => $selected_atom_site,
                                       'keep_original' => $keep_original,
                                       'tracked_auth_alt_ids' =>
                                           \%tracked_auth_alt_ids,
                                       'last_atom_id' => $last_atom_id
                                     } );
                for my $assigned_hetatom_id ( @{ $assigned_hetatom_ids } ) {
                    next if $last_atom_id > $assigned_hetatom_id;

                    $last_atom_id = $assigned_hetatom_id;
                }
            }

            hybridization( $parameters, $residue_site );
            connect_atoms( $parameters, $residue_site );

            # Retrieves bond parameter values.
            my @rotamer_angle_ids = @{
                $rotamer_angle_split_groups->{$residue_unique_key}{'atom_ids'}
            };

            my %rotamer_angles = ();
            my %rotamer_angles_atom_ids_tbl = ();
            for my $id ( @rotamer_angle_ids ) {
                my $rotamer_id = $rotamer_angle->{$id}{'rotamer_id'};
                my $origin_atom_ids_key =
                    join ',',
                    map { defined $_ ? $_ : '?' }
                    map { $rotamer_angle->{$id}{$_} }
                    ( 'atom_1_id', 'atom_2_id', 'atom_3_id', 'atom_4_id' );

                next if exists $rotamer_angles{$rotamer_id};

                my @related_ids =
                    keys %{ $rotamer_to_bond_parameter_tbl{$rotamer_id} };
                for my $related_id ( @related_ids ) {
                    my $angle_name = $rotamer_angle->{$related_id}{'type'};
                    my $current_residue_unique_key =
                        unique_residue_key( $rotamer_angle->{$related_id} );

                    my $angle_value;
                    if( defined $rotamer_angle->{$related_id}{'units'} &&
                        $rotamer_angle->{$related_id}{'units'} eq 'degrees' ) {
                        $angle_value =
                            $pi * $rotamer_angle->{$related_id}{'value'} / 180.0;
                    } else {
                        $angle_value = $rotamer_angle->{$related_id}{'value'};
                    }

                    $rotamer_angles{"$rotamer_id"}{$angle_name} =
                        [ $angle_value ];
                    $rotamer_angles_atom_ids_tbl{"$rotamer_id"}{$angle_name} =
                        $origin_atom_ids_key;
                }
            }

            # Updating the atom site as there more duplicated pseudo atoms.
            for my $atom_id ( sort { $a <=> $b } keys %{ $residue_site } ) {
                my $origin_atom_id =
                    $residue_site->{$atom_id}{'origin_atom_id'};

                next if ! defined $origin_atom_id ||
                    ! exists $target_atom_site->{$origin_atom_id};

                if( ! $keep_original ) {
                    $delete_original{$origin_atom_id} = 1;
                }

                delete $residue_site->{$origin_atom_id};
            }

            if( $do_rotable_bonds ) {
                rotatable_bonds( $parameters,
                                 $residue_site,
                                 { ( 'include_hetatoms' =>
                                     ( %{ $struct_conn } &&
                                       $include_hetatoms ? 1 : 0 ) ) } );
            }
            if( $do_stretchable_bonds ) {
                stretchable_bonds( $parameters,
                                   $residue_site,
                                   { ( 'include_hetatoms' =>
                                       ( %{ $struct_conn } &&
                                         $include_hetatoms ? 1 : 0 ) ) } );
            }
            if( $do_bendable_angles ) {
                bendable_angles( $parameters,
                                 $residue_site,
                                 { ( 'include_hetatoms' =>
                                         ( %{ $struct_conn } &&
                                           $include_hetatoms ? 1 : 0 ) ) } );
            }

            # Generates rotational model.
            rotation_translation( $parameters, $residue_site );

            for my $atom_id ( sort { $a <=> $b } keys %{ $residue_site } ) {
                my $atom_name = $residue_site->{$atom_id}{'label_atom_id'};
                my $group_PDB = $residue_site->{$atom_id}{'group_PDB'};

                next if $group_PDB eq 'ATOM' &&
                    exists $exclude_atom_names{$atom_name};

                my $current_residue_unique_key =
                    unique_residue_key( $residue_site->{$atom_id} );
                my $changed_residue_unique_key = $current_residue_unique_key;
                if( $include_hetatoms && $group_PDB eq 'HETATM' ) {
                    $changed_residue_unique_key =
                        change_unique_residue_key( $current_residue_unique_key,
                                                   { 'pdbx_auth_alt_id' => '?' } );
                }

                for my $rotamer_id ( sort { $a <=> $b } keys %rotamer_angles ) {
                    my $rotamer_angles = $rotamer_angles{$rotamer_id};
                    # Only checks if any bond parameters are present. If no, it
                    # should be ignored.
                    my $bond_parameters = collect_bond_parameters(
                        { $atom_id => $residue_site->{$atom_id} }
                    )->{$current_residue_unique_key};

                    next if ! defined $bond_parameters || ! %{ $bond_parameters };

                    %rotamer_atom_site =
                        ( %rotamer_atom_site,
                          %{ generate_pseudo(
                                 { 'parameters' => $parameters,
                                   'atom_site' => $residue_site,
                                   'atom_specifier' => { 'id' => [ $atom_id ] },
                                   'bond_parameter_values' => $rotamer_angles,
                                   'last_atom_id' => $last_atom_id,
                                    # TODO: check if it is a good idea to have
                                    # $rotamer_id as 'label_alt_id'.
                                   'alt_group_id' => $rotamer_id,
                                   'auth_alt_group_id' =>
                                       ( ( $include_hetatoms && $group_PDB eq 'HETATM' ) ?
                                         $residue_site->{$atom_id}{'pdbx_auth_alt_id'} :
                                         $residue_site->{$atom_id}{'label_alt_id'} ),
                                   'selection_state' => 'T' } ) } );
                    $last_atom_id++;

                    if( ! $keep_original || $group_PDB eq 'HETATM' ) {
                        delete $target_atom_site->{$atom_id};
                    }
                }
            }
        }

        if( ! $keep_original ) {
            for my $origin_atom_id ( sort keys %delete_original ) {
                delete $target_atom_site->{$origin_atom_id};
            }
        }

        # my $atom_site_split_groups =
        #     split_by( { 'atom_site' => $target_atom_site,
        #                 'append_dot' => 1 } );

        # my %rotamer_angles;
        # my %rotamer_angles_atom_ids_tbl = ();
        # my %related_unique_residue_keys = ();
        # my %tracked_auth_alt_ids = ();
        # my %delete_original = ();
        # my $last_atom_id = max( keys %{ $atom_site } );
        # for my $residue_unique_key ( sort keys %{ $atom_site_split_groups } ) {
        #     my $current_target_atom_site =
        #         filter( { 'atom_site' => $atom_site,
        #                   'include' =>
        #                   { 'id' =>
        #                         $atom_site_split_groups->{$residue_unique_key}
        #                                                  {'atom_ids'} } } );
        #     my $residue_site =
        #         filter_by_unique_residue_key(
        #             $current_target_atom_site,
        #             $residue_unique_key,
        #             1
        #     );

        #     hybridization( $parameters, $residue_site );
        #     connect_atoms( $parameters, $residue_site );

        #     # TODO: check if the overwriting the global variable is not
        #     # dangerous.
        #     my $additional_struct_conn =
        #         struct_conn_from_connections( $parameters,
        #                                       $residue_site,
        #                                       $struct_conn );
        #     $struct_conn = {
        #         ( defined $struct_conn ? %{ $struct_conn } : () ),
        #         %{ $additional_struct_conn }
        #     };

        #     my $struct_conn_atom_ids =
        #         struct_conn_atom_ids( $residue_site, $struct_conn );

        #     if( @{ $struct_conn_atom_ids } ) {
        #         my $assigned_hetatom_ids =
        #             assign_hetatoms( $parameters,
        #                              $residue_site,
        #                              $struct_conn,
        #                              { 'sidechains_only' => 1,
        #                                'ref_atom_site' => $selected_atom_site,
        #                                'keep_original' => $keep_original,
        #                                'tracked_auth_alt_ids' =>
        #                                    \%tracked_auth_alt_ids,
        #                                'last_atom_id' => $last_atom_id
        #                              } );
        #         for my $assigned_hetatom_id ( @{ $assigned_hetatom_ids } ) {
        #             next if $last_atom_id > $assigned_hetatom_id;

        #             $last_atom_id = $assigned_hetatom_id;
        #         }
        #     }

        #     # Tracking the relatedness of the residues.
        #     my $unique_residue_keys =
        #         struct_conn_residue_keys( $parameters,
        #                                   $residue_site,
        #                                   $struct_conn );
        #     for my $unique_residue_key (
        #         keys %{ $unique_residue_keys } ) {
        #         for my $related_unique_residue_key (
        #             keys %{ $unique_residue_keys->{$unique_residue_key} } ) {
        #             $related_unique_residue_keys{$unique_residue_key}
        #                                         {$related_unique_residue_key} = 1;
        #             $related_unique_residue_keys{$related_unique_residue_key}
        #                                         {$unique_residue_key} = 1;
        #         }
        #     }

        #     # Updating the target's atom site as there more duplicated pseudo
        #     # atoms.
        #     # HACK: the copying should be done by function and not depend on
        #     # sorting order.
        #     for my $atom_id ( sort { $a <=> $b } keys %{ $residue_site } ) {
        #         my $origin_atom_id =
        #             $residue_site->{$atom_id}{'origin_atom_id'};

        #         next if ! defined $origin_atom_id ||
        #             ! exists $target_atom_site->{$origin_atom_id};

        #         $target_atom_site->{$atom_id} = $residue_site->{$atom_id};
        #         $target_atom_site_only->{$atom_id} = $residue_site->{$atom_id};
        #         $selected_atom_site->{$atom_id} = $residue_site->{$atom_id};

        #         if( ! $keep_original ) {
        #             $delete_original{$origin_atom_id} = 1;
        #         }

        #         delete $target_atom_site_only->{$origin_atom_id};
        #         delete $selected_atom_site->{$origin_atom_id};
        #         delete $residue_site->{$origin_atom_id};

        #         delete $selected_atom_site->{$atom_id}{'bendable_angles'};
        #         delete $selected_atom_site->{$atom_id}{'rotatable_bonds'};
        #         delete $selected_atom_site->{$atom_id}{'stretchable_bonds'};
        #     }

        #     if( $do_rotable_bonds ) {
        #         rotatable_bonds( $parameters,
        #                          $residue_site,
        #                          { ( 'include_hetatoms' =>
        #                              ( %{ $struct_conn } &&
        #                                $include_hetatoms ? 1 : 0 ) ) } );
        #     }
        #     if( $do_stretchable_bonds ) {
        #         stretchable_bonds( $parameters,
        #                            $residue_site,
        #                            { ( 'include_hetatoms' =>
        #                                ( %{ $struct_conn } &&
        #                                  $include_hetatoms ? 1 : 0 ) ) } );
        #     }
        #     if( $do_bendable_angles ) {
        #         bendable_angles( $parameters,
        #                          $residue_site,
        #                          { ( 'include_hetatoms' =>
        #                                  ( %{ $struct_conn } &&
        #                                    $include_hetatoms ? 1 : 0 ) ) } );
        #     }

        #     # Generates rotational model.
        #     rotation_translation( $parameters, $residue_site );

        #     # Determines the key that will connect 'atom_site' and
        #     # '_[local]_rotamer_bond_parameter' data.
        #     my $residue_angle_key;
        #     if( exists $rotamer_angle->{$rotamer_ids[0]}{'label_seq_id'} &&
        #         exists $rotamer_angle->{$rotamer_ids[0]}{'label_asym_id'} &&
        #         exists $rotamer_angle->{$rotamer_ids[0]}{'label_alt_id'} &&
        #         exists $rotamer_angle->{$rotamer_ids[0]}{'pdbx_PDB_model_num'}){
        #         $residue_angle_key = $residue_unique_key;
        #         # HACK: check if all values in 'phi_min' and 'psi_min' has length
        #         # to 'phi_max' and 'psi_max' of 10 accordingly.
        #     } elsif( ( exists $rotamer_angle->{$rotamer_ids[0]}{'label_comp_id'} &&
        #                exists $rotamer_angle->{$rotamer_ids[0]}{'phi'} &&
        #                exists $rotamer_angle->{$rotamer_ids[0]}{'psi'} ) ||
        #              ( exists $rotamer_angle->{$rotamer_ids[0]}{'label_comp_id'} &&
        #                exists $rotamer_angle->{$rotamer_ids[0]}{'phi_min'} &&
        #                exists $rotamer_angle->{$rotamer_ids[0]}{'psi_min'} &&
        #                exists $rotamer_angle->{$rotamer_ids[0]}{'phi_max'} &&
        #                exists $rotamer_angle->{$rotamer_ids[0]}{'psi_max'} ) ) {
        #         rotatable_bonds( $parameters, $residue_site,
        #                          { 'include_mainchain' => 1 } );
        #         my $dihedral_angles = collect_dihedral_angles( $residue_site );

        #         # Calculates phi and psi angles.
        #         my $phi;
        #         my $psi;
        #         if( %{ $dihedral_angles } ) {
        #             if( defined $dihedral_angles->{$residue_unique_key}{'phi'}{'value'} &&
        #                 defined $dihedral_angles->{$residue_unique_key}{'psi'}{'value'} ) {
        #                 $phi =
        #                     180.00 *
        #                     $dihedral_angles->{$residue_unique_key}{'phi'}{'value'} /
        #                     $pi;
        #                 $psi =
        #                     180.00 *
        #                     $dihedral_angles->{$residue_unique_key}{'psi'}{'value'} /
        #                     $pi;
        #             } else {
        #                 die 'phi and psi angles cannot be determined due to ' .
        #                     "the lack of required main-chain atoms.\n";
        #             }
        #         }

        #         # Checks the closest candidate for existing backbone dihedral
        #         # angle combination.
        #         my $residue_name = extract( $residue_site,
        #                                     { 'data' => [ 'label_comp_id' ],
        #                                       'is_list' => 1 } )->[0];
        #         my $closest_key_candidate;
        #         for my $rotamer_unique_key (keys %{$rotamer_angle_split_groups}){
        #             # TODO: there is a room for optimization here by generating
        #             # hash table.
        #             my ( $angle_residue_name, $angle_phi, $angle_psi ) =
        #                 split /,/, $rotamer_unique_key;

        #             next if $residue_name ne $angle_residue_name;

        #             if( $phi >= $angle_phi && $phi < $angle_phi + 10.0 &&
        #                 $psi >= $angle_psi && $psi < $angle_psi + 10.0 ) {
        #                 $closest_key_candidate =
        #                     "$angle_residue_name,$angle_phi,$angle_psi";
        #                 last;
        #             }
        #         }
        #         $residue_angle_key = $closest_key_candidate;
        #     } elsif( exists $rotamer_angle->{$rotamer_ids[0]}{'label_comp_id'} ){
        #         $residue_angle_key = extract( $residue_site,
        #                                       { 'data' => [ 'label_comp_id' ],
        #                                         'is_list' => 1 } )->[0];
        #     }

        #     next if ! defined $residue_angle_key;

        #     # HACK: more robust check should be implemented.
        #     if( ! defined $rotamer_angle_split_groups->{$residue_angle_key} ) {
        #         my @key_parts = split /,/, $residue_angle_key;
        #         $key_parts[$#key_parts] =
        #             $key_parts[$#key_parts] eq '.' ?
        #             '?' : $key_parts[$#key_parts];
        #         $residue_angle_key = join ',', @key_parts;
        #     }

        #     next if ! defined $rotamer_angle_split_groups->{$residue_angle_key};

        #     for my $id ( sort { $a <=> $b }
        #                  @{ $rotamer_angle_split_groups->{$residue_angle_key}
        #                                                  {'atom_ids'} } ) {
        #         my $rotamer_id = $rotamer_angle->{$id}{'rotamer_id'};
        #         my $label_seq_id = $rotamer_angle->{$id}{'label_seq_id'};
        #         my $angle_name = $rotamer_angle->{$id}{'type'};
        #         my $origin_atom_ids_key =
        #             join ',',
        #             map { defined $_ ? $_ : '?' }
        #             map { $rotamer_angle->{$id}{$_} }
        #             ( 'atom_1_id', 'atom_2_id', 'atom_3_id', 'atom_4_id' );

        #         # TODO: refactor or just move to separate module that deals with
        #         # retracting proper bond parameters.
        #         my $changed_residue_unique_key = $residue_unique_key;
        #         if( $include_hetatoms && $label_seq_id eq '.' ) {
        #             my ( $site_id ) =
        #                 grep { $_ ne '.' }
        #                 reverse
        #                 map { $rotamer_angle->{$id}{$_} }
        #                 grep { exists $rotamer_angle->{$id}{$_} }
        #                     ( 'site_1_id', 'site_2_id', 'site_3_id', 'site_4_id' );
        #             $site_id //= '1';
        #             $changed_residue_unique_key =
        #                 change_unique_residue_key( $changed_residue_unique_key,
        #                                            { 'pdbx_auth_alt_id' => $site_id } );
        #         }

        #         my $angle_value;
        #         if( defined $rotamer_angle->{$id}{'units'} &&
        #             $rotamer_angle->{$id}{'units'} eq 'degrees' ) {
        #             $angle_value = $pi * $rotamer_angle->{$id}{'value'} / 180.0;
        #         } else {
        #             $angle_value = $rotamer_angle->{$id}{'value'};
        #         }

        #         $rotamer_angles{$changed_residue_unique_key}{"$rotamer_id"}{$angle_name} =
        #             [ $angle_value ];
        #         $rotamer_angles_atom_ids_tbl{$changed_residue_unique_key}
        #                                     {"$rotamer_id"}
        #                                     {$angle_name} = $origin_atom_ids_key;
        #     }
        # }

        # if( ! $keep_original ) {
        #     for my $origin_atom_id ( sort keys %delete_original ) {
        #         delete $target_atom_site->{$origin_atom_id};
        #     }
        # }

        # my %rotamer_atom_site;
        # $last_atom_id = max( keys %{ $atom_site } ); # Resets id for printing.
        # for my $atom_id ( sort { $a <=> $b } keys %{ $target_atom_site_only } ) {
        #     my $group_PDB = $target_atom_site_only->{$atom_id}{'group_PDB'};

        #     my $residue_unique_key =
        #         unique_residue_key( $selected_atom_site->{$atom_id} );

        #     my $bond_parameters = collect_bond_parameters(
        #         { $atom_id => $selected_atom_site->{$atom_id} }
        #     )->{$residue_unique_key};

        #     my %related_residue_unique_keys = ();
        #     if( exists $related_unique_residue_keys{$residue_unique_key} ) {
        #         for my $related_unique_residue_key (
        #             keys %{ $related_unique_residue_keys{$residue_unique_key} } ) {
        #             $related_residue_unique_keys{$related_unique_residue_key} = 1;

        #             next if ! exists $related_unique_residue_keys{$related_unique_residue_key};

        #             for my $reverse_unique_residue_key (
        #                 keys %{ $related_unique_residue_keys{$related_unique_residue_key} } ) {
        #                 $related_residue_unique_keys{$reverse_unique_residue_key} = 1;
        #             }
        #         }
        #     }

        #     # TODO: refactoring is needed.
        #     if( ! exists $rotamer_angles{$residue_unique_key} &&
        #         $target_atom_site->{$atom_id}{'group_PDB'} eq 'HETATM'  ) {
        #         delete $target_atom_site->{$atom_id};
        #     }

        #     next if ! exists $rotamer_angles{$residue_unique_key};

        #     for my $rotamer_id ( sort { $a <=> $b }
        #                          keys %{ $rotamer_angles{$residue_unique_key} } ) {
        #         my $rotamer_angles =
        #             $rotamer_angles{$residue_unique_key}{$rotamer_id};

        #         # Adds missing rotamer angles.
        #         my %include_rotamers = ();
        #         for my $related_unique_residue_key ( sort keys %related_residue_unique_keys ) {
        #             # TODO: refactoring is needed as the naming convention is
        #             # very similar to other variables.
        #             my $bond_parameter_atom_ids_tbl =
        #                 $rotamer_angles_atom_ids_tbl{$related_unique_residue_key}
        #                                             {$rotamer_id};

        #             next if ! defined $bond_parameter_atom_ids_tbl;

        #             # TODO: think about situations where there are defined
        #             # bond parameters that do not include all the atoms.
        #             for my $bond_parameter_name ( sort keys %{ $bond_parameter_atom_ids_tbl } ) {
        #                 my $origin_atom_ids_key =
        #                     $bond_parameter_atom_ids_tbl->{$bond_parameter_name};

        #                 next if ! exists $bond_parameters->{$bond_parameter_name};

        #                 next if $origin_atom_ids_key ne '?,?,?,?' &&
        #                     $origin_atom_ids_key ne $bond_parameters->{$bond_parameter_name}
        #                                                               {'origin_atom_ids_key'};

        #                 $include_rotamers{$related_unique_residue_key} = 1;
        #             }
        #         }

        #         for my $related_unique_residue_key ( sort keys %related_residue_unique_keys ) {
        #             next if ! exists $rotamer_angles{$related_unique_residue_key} ||
        #                     ! exists $rotamer_angles{$related_unique_residue_key}{$rotamer_id} ||
        #                     ! exists $include_rotamers{$related_unique_residue_key};

        #             $rotamer_angles = {
        #                 %{ $rotamer_angles },
        #                 %{ $rotamer_angles{$related_unique_residue_key}{$rotamer_id} }
        #             };
        #         }

        #         next if ! exists $include_rotamers{$residue_unique_key} &&
        #             $selected_atom_site->{$atom_id}{'group_PDB'} eq 'HETATM';

        #         %rotamer_atom_site =
        #             ( %rotamer_atom_site,
        #               %{ generate_pseudo(
        #                      { 'parameters' => $parameters,
        #                        'atom_site' => $selected_atom_site,
        #                        'atom_specifier' => { 'id' => [ $atom_id ] },
        #                        'bond_parameter_values' => $rotamer_angles,
        #                        'last_atom_id' => $last_atom_id,
        #                         # TODO: check if it is a good idea to have
        #                         # $rotamer_id as 'label_alt_id'.
        #                        'alt_group_id' => $rotamer_id,
        #                        'auth_alt_group_id' =>
        #                            ( ( $include_hetatoms &&
        #                                $selected_atom_site->{$atom_id}{'group_PDB'} eq 'HETATM' ) ?
        #                              $selected_atom_site->{$atom_id}{'pdbx_auth_alt_id'} :
        #                              $selected_atom_site->{$atom_id}{'label_alt_id'} ),
        #                        'selection_state' => 'T' } ) } );

        #         $last_atom_id++;
        #     }

        #     if( ! $keep_original ||
        #         $target_atom_site->{$atom_id}{'group_PDB'} eq 'HETATM' ) {
        #         delete $target_atom_site->{$atom_id};
        #     }
        # }

        if( $optimise_ligands ) {
            my $ligand_groups =
                split_by( { 'atom_site' =>
                                filter_new( \%rotamer_atom_site,
                                            { 'include' =>
                                              { 'group_PDB' => [ 'HETATM' ] } } ),
                            'attributes' => [
                                'label_seq_id', 'label_asym_id',
                                'pdbx_PDB_model_num', 'auth_seq_id',
                                'auth_asym_id'
                            ] } );

            # Ligands are bein clusterised in order to reduce the count of
            # suggested ligand positions.
            my %cluster_core_ligands = ();
            for my $group_id ( sort keys %{ $ligand_groups } ) {
                # HACK: has to be generalised and not only used with ions.
                my $cluster = new DBScan();
                for my $atom_id ( @{ $ligand_groups->{$group_id}{'atom_ids'} } ) {
                    $cluster->add_point(
                        [ $rotamer_atom_site{$atom_id}{'Cartn_x'},
                          $rotamer_atom_site{$atom_id}{'Cartn_y'},
                          $rotamer_atom_site{$atom_id}{'Cartn_z'} ],
                        $atom_id
                    );
                }
                # TODO: parametrise the distance.
                $cluster->dbscan( $dbscan_distance,
                                  { 'min_points' => $dbscan_min } );

                # Chooses the most energetically and structurally stable member
                # of the cluster.
                for my $label ( @{ $cluster->get_labels() } ) {
                    my $atom_ids = $cluster->get_ids_by_label( $label );
                    my ( $lowest_energy_member ) =
                        sort { $a->{'value'} <=> $b->{'value'} }
                        map { $rotamer_energy->{$_} }
                        uniq map { $rotamer_atom_site{$_}{'label_alt_id'} }
                        @{ $atom_ids };
                    $cluster_core_ligands{$lowest_energy_member->{'rotamer_id'}} = 1;
                }
            }
            %rotamer_atom_site =
                map { $_ => $rotamer_atom_site{$_} }
                grep { exists $cluster_core_ligands{$rotamer_atom_site{$_}{'label_alt_id'}} }
                keys %rotamer_atom_site;
        }

        if( $add_B_iso ) {
            for my $atom_id ( keys %rotamer_atom_site ) {
                next if ! defined $rotamer_atom_site{$atom_id}{'label_alt_id'};

                $rotamer_atom_site{$atom_id}{'B_iso_or_equiv'} =
                    $rotamer_energy->{$rotamer_atom_site{$atom_id}{'label_alt_id'}}
                                     {'value'};
            }
        }

        $pdbx->{'_atom_site'}{'data'} = {
            %{ $target_atom_site }, %rotamer_atom_site
        };

        to_pdbx( $pdbx,
                 { 'tags' => \@tags,
                   'default_empty_values' => { 'pdbx_auth_alt_id' => '.' },
                   'add_attributes' =>
                       { '_atom_site' =>
                             [ ( $add_B_iso ? ( 'B_iso_or_equiv' ) : () ),
                               '[local]_selection_state' ] } } );
    } elsif( $add_hydrogens ) {
        # Selects all atoms if no specific atoms are selected.
        if( ! %{ $target_atom_site } ) {
            $target_atom_site = $atom_site;
            $selected_atom_site = $atom_site;
            mark_selection( $target_atom_site,
                            { 'target' => [ keys %{ $target_atom_site } ] } );
        }

        my $atom_site_split_groups =
            split_by( { 'atom_site' => $selected_atom_site,
                        'attributes' => [ 'pdbx_PDB_model_num',
                                          'label_alt_id' ],
                        'append_dot' => 1 } );

        my %hydrogen_site;
        my $last_atom_id = max( keys %{ $atom_site } );
        my @visited_atom_ids;
        for my $atom_site_identifier ( sort keys %{ $atom_site_split_groups } ){
            my $current_atom_site =
                filter( { 'atom_site' => $target_atom_site,
                          'include' =>
                              { 'id' =>
                                    $atom_site_split_groups->
                                        {$atom_site_identifier}{'atom_ids'} } } );
            my $reference_atom_site =
                filter( { 'atom_site' => $selected_atom_site,
                          'include' =>
                              { 'id' =>
                                    $atom_site_split_groups->
                                        {$atom_site_identifier}{'atom_ids'} } } );

            connect_atoms( $parameters, $current_atom_site );
            hybridization( $parameters, $current_atom_site );
            # TODO: check how determination of bond parameters could be reduced,
            # because it increases the computation time.
            connect_atoms( $parameters, $reference_atom_site );
            hybridization( $parameters, $reference_atom_site );

            my $hydrogen_site =
                add_hydrogens( $parameters, $current_atom_site,
                               { 'last_atom_id' => $last_atom_id,
                                 'use_origins_alt_group_id' => 1,
                                 'use_existing_connections' => 1,
                                 'use_existing_hybridizations' => 1,
                                 'add_only_clear_positions' =>
                                     $add_clear_positions,
                                 'exclude_by_atom_ids' => \@visited_atom_ids,
                                 'reference_atom_site' => $reference_atom_site} );
            %hydrogen_site = ( %hydrogen_site, %{ $hydrogen_site } );

            push @visited_atom_ids, keys %{ $current_atom_site };

            $last_atom_id = max( keys %hydrogen_site );
        }

        $pdbx->{'_atom_site'}{'data'} = { %{ $atom_site }, %hydrogen_site };

        to_pdbx( $pdbx,
                 { 'tags' => \@tags,
                   'add_attributes' =>
                       { '_atom_site' => [ '[local]_selection_state' ] } } );
    } elsif( scalar @add_ligands > 0 ) {
        my $last_atom_id = max( keys %{ $atom_site } ) + 1;
        my $last_chain_id = increase_chain_id(
            [ grep { $_ ne '.' && $_ ne '?' }
              map { $atom_site->{$_}{'label_asym_id'} }
              keys %{ $atom_site } ],
            1
        );

        my ( $last_auth_seq_id ) =
            sort { $b <=> $a }
            grep { $_ ne '.' && $_ ne '?' }
            map { $atom_site->{$_}{'auth_seq_id'} }
            keys %{ $atom_site };
        $last_auth_seq_id++;

        my %ligand_site = ();
        for my $add_ligand ( @add_ligands ) {
            if( ! exists $heteroatom_extension->{$add_ligand}  ) {
                error(
                    { 'program' => $0,
                      'filename' => $pdbx_file,
                      'message' =>
                          "\"$add_ligand\" cannot be added. Check moieties " .
                          "that are available using --list-ligands option.\n" } );
            }

            for my $pseudo_atom_id ( sort { $a <=> $b }
                                     keys %{ $moieties->{$add_ligand} } ) {
                $ligand_site{$last_atom_id} =
                    clone $moieties->{$add_ligand}{$pseudo_atom_id};
                $ligand_site{$last_atom_id}{'group_PDB'} = 'HETATM';
                $ligand_site{$last_atom_id}{'id'} = $last_atom_id;
                $ligand_site{$last_atom_id}{'label_asym_id'} = $last_chain_id;
                # TODO: check if it is OK to assume that it is always 1 if not
                # specified.
                $ligand_site{$last_atom_id}{'label_entity_id'} = 1;
                $ligand_site{$last_atom_id}{'auth_seq_id'} = $last_auth_seq_id;
                $last_atom_id++;
            }

            $last_chain_id = increase_chain_id( [ $last_chain_id ], 1 );
            $last_auth_seq_id++;
        }

        $pdbx->{'_atom_site'}{'data'} = { %{ $atom_site }, %ligand_site };

        to_pdbx( $pdbx,
                 { 'tags' => \@tags,
                   'add_attributes' =>
                       { '_atom_site' => [ '[local]_selection_state' ] } } );
    } else {
        error(
            { 'program' => $0,
              'filename' => $pdbx_file,
              'message' => "no options were chosen for atom additions.\n" } );
    }
}
