#!/usr/bin/perl

use strict;
use warnings;

use autodie;
use Getopt::Long;

use ForceField::Parameters();
use ForceField::Bonded qw( general );
use ForceField::NonBonded qw( general );
use Logging qw( error
                warning );
use PDBxParser qw( filter
                   obtain_pdbx_data
                   raw2indexed
                   to_pdbx );
use SidechainInteractions;
use Version qw( $VERSION );

Getopt::Long::Configure qw( gnu_getopt );

our $VERSION = $VERSION;

#*rotag_predict [options] --side-chains [--] <cif-file>...
#*    predict side-chain positions.
#*
#*Usage:
#*    rotag_predict --side-chains input.cif > output.cif
#*
#*Options:
#*    -S, --side-chains
#*                        predicts all probable side-chain positions according to
#*                        the given energy threshold.
#*    -F, --format <format>
#*                        print out graph data in specified formats
#*                        (default: tsv).
#*    -v, --version
#*                        prints version.

# --------------------------------- Options ----------------------------------- #

my $predict_sidechains = 0;
my $output_categories = '_atom_site';
my $output_format = 'pdbx';
my @category_list =
    ( '_atom_site', '_[local]_rotamer_angle', '_[local]_rotamer_energy' );
my @attribute_list =
    ( 'label_seq_id', 'label_comp_id', 'label_entity_id', 'label_alt_id',
      'rotamer_id', 'type', 'value', );

local $SIG{__WARN__} = sub {
    warning( { 'program' => $0, 'message' => @_ } );
};

local $SIG{__DIE__} = sub {
    error( { 'program' => $0, 'message' => @_ } );
};

GetOptions(
    'side-chains|S' => sub { $predict_sidechains = 1 },
    'format|F=s' => \$output_format,
    'help|h' => sub {
                        open my $fh, '<', $0;
                        while( <$fh> ) {
                            my ( $help_message ) = $_ =~ m/^#(\*.*)/;
                            if( $help_message ) {
                                $help_message =~ s/^\*$/ /smgx;
                                $help_message =~ s/^\*//smgx;
                                print $help_message, "\n";
                            }
                        }
                        close $fh;
                        exit;
                    },
    'version|v' => sub { print $VERSION, "\n"; exit; }
) or error( { 'program' => $0,
              'message' => "mistake in command line argument.\n" } );

# ----------------------------------- Main ------------------------------------ #

local @ARGV = ( q{-} ) unless @ARGV;

$output_categories =~ s/ //g;
my @output_categories = split /,/, $output_categories;

my $parameters = Parameters->new();
my $pi = $parameters->{'_[local]_constants'}{'pi'};
my $interaction_atom_names = $parameters->{'_[local]_interaction_atom_names'};

for my $pdbx_file ( @ARGV ) {
    my $pdbx = obtain_pdbx_data( $pdbx_file, \@category_list );
    raw2indexed( $pdbx,
                 { 'attributes' => { '_atom_site' => [ 'id' ],
                                     '_[local]_rotamer_angle' => [ 'id' ],
                                     '_[local]_rotamer_energy' => [ 'id' ] } } );

    # Reads file path, stdin and '-' operator.
    my $atom_site = $pdbx->{'_atom_site'}{'data'};

    if( ! defined $atom_site ) {
        warning( { 'program' => $0,
                   'message' => "no atom sites were detected.\n" } );
        next;
    }

    my $selected_atom_site =
        filter( { 'atom_site' => $atom_site,
                  'include' => { '[local]_selection_state' => [ 'T', 'S' ] } } );
    my $target_atom_site =
        filter( { 'atom_site' => $selected_atom_site,
                  'include' => { '[local]_selection_state' => [ 'T' ] } } );
    my $target_atom_ids =
        filter( { 'atom_site' => $target_atom_site,
                  'include' => { '[local]_selection_state' => [ 'T' ] },
                  'exclude' => { 'label_atom_id' => $interaction_atom_names },
                  'data' => [ 'id' ],
                  'is_list' => 1 } );

    if( $predict_sidechains ) {
        my $rotamer_angles = $pdbx->{'_[local]_rotamer_angle'}{'data'};
        my $rotamer_energies = $pdbx->{'_[local]_rotamer_energy'}{'data'};

        if( ! defined $rotamer_angles ) {
            warning( { 'program' => $0,
                       'message' => "no rotamer angles were detected.\n" } );
            next;
        }

        my $sidechain_interactions = SidechainInteractions->new(
            $parameters, $atom_site, $rotamer_angles, $rotamer_energies
        );

        # $interaction_graph->predict_sidechains( {
        #     'rotamer_angles' => $rotamer_angles,
        #     'rotamer_energies' => $rotamer_energies,
        #     'non_bonded_potential' =>
        #         \&ForceField::NonBonded::general,
        #     'bonded_potential' =>
        #         \&ForceField::Bonded::general,
        # } );

        if( $output_format eq 'pdbx' ) {
            # # Prints out the PDBx.
            # to_pdbx( $pdbx, { 'add_attributes' =>
            #                       { '_atom_site' => [ '[local]_selection_state',
            #                                           '[local]_selection_group' ] } } );
        } elsif( $output_format eq 'tsv' ) {
            # $interaction_graph->to_tsv();
        }
    } else {
        error(
            { 'program' => $0,
              'filename' => $pdbx_file,
              'message' => "no options were chosen for atom additions.\n" } );
    }
}
