#!/usr/bin/perl

use strict;
use warnings;

use autodie;
use Carp;
use Clone qw( clone );
use Getopt::Long;
use List::MoreUtils qw( uniq );
use Try::Tiny;

use Logging qw( error
                warning );
use PDBxParser qw( filter
                   filter_by_unique_residue_key
                   obtain_pdbx_data
                   raw2indexed
                   to_pdbx
                   to_csv
                   unique_residue_key );
use StructConn qw( counter_struct_conn
                   create_struct_conn );
use Version qw( $VERSION );

Getopt::Long::Configure qw( gnu_getopt );

our $VERSION = $VERSION;

#*rotag_connect [options] (--covale|--disulf|--hydrog|--metalc) \
#*    <groups-to-connect> [--] <cif-file>...
#*    connects and/or marks interactions between atoms of two or more atom
#*    groups by adding '_struct_conn' loop entries.
#*
#*Usage:
#*    rotag_connect --metalc '1,2' input.cif > output.cif
#*    rotag_connect --covale '1,2;3,4' input.cif > output.cif
#*    rotag_connect --metalc '1,2,3,4' --hydrog '4,5' input.cif > output.cif
#*
#*Options:
#*    --covale <group>,<group>[;<group>,<group>;...]
#*                        connects atoms by covalent bond.
#*    --disulf <group>,<group>[;<group>,<group>;...]
#*                        connects atoms by disulfide bond.
#*    --hydrog <group>,<group>[;<group>,<group>;...]
#*                        marks atoms participating in hydrogen bond.
#*    --metalc <group>,<group>[;<group>,<group>;...]
#*                        marks atoms participating in metal coordination.
#*    --tags <tag>[,<tag>...]
#*                        select PDBx categories that will be in the output
#*                        (default: '_atom_site,_struct_conn').
#*    -F, --format <format>
#*                        output format (default: pdbx | csv).
#*    -v, --version
#*                        print version.

# --------------------------------- Options ----------------------------------- #

my $covalent_queries = '';
my $disulfide_queries = '';
my $hydrogen_queries = '';
my $metalc_queries = '';
my $tags = '_atom_site,_struct_conn';
my $output_format = 'pdbx';
my @category_list = ( '_atom_site', '_struct_conn' );

local $SIG{__WARN__} = sub {
    warning( { 'program' => $0,
               'message' => @_,
               'filename' => join( ', ', @ARGV ) } );
};

local $SIG{__DIE__} = sub {
    error( { 'program' => $0,
             'message' => @_,
             'filename' => join( ', ', @ARGV ) } );
};

GetOptions(
    'covale=s' => \$covalent_queries,
    'disulf=s' => \$disulfide_queries,
    'hydrog=s' => \$hydrogen_queries,
    'metalc=s' => \$metalc_queries,
    'tags=s' => \$tags,
    'format|F=s' => \$output_format,
    'help|h' => sub {
                        open my $fh, '<', $0;
                        while( <$fh> ) {
                            my ( $help_message ) = $_ =~ m/^#(\*.*)/;
                            if( $help_message ) {
                                $help_message =~ s/^\*$/ /smgx;
                                $help_message =~ s/^\*//smgx;
                                print $help_message, "\n";
                            }
                        }
                        close $fh;
                        exit;
                    },
    'version|v' => sub { print $VERSION, "\n"; exit; }
)  or error( { 'program' => $0,
               'message' => "mistake in command line argument.\n" } );

# ----------------------------------- Main ------------------------------------ #

local @ARGV = ( q{-} ) unless @ARGV;

$tags =~ s/ //g;
my @tags = split /,/, $tags;

$covalent_queries =~ s/ //g;;
$disulfide_queries =~ s/ //g;;
$hydrogen_queries =~ s/ //g;;
$metalc_queries =~ s/ //g;;

for my $pdbx_file ( @ARGV ) {
    my $pdbx_data = obtain_pdbx_data( $pdbx_file, \@category_list );

    if( ! defined $pdbx_data->{'_atom_site'}{'data'} ) {
        warning( { 'program' => $0,
                   'message' => "no atom sites were detected.\n" } );
        next;
    }

    raw2indexed( $pdbx_data,
                 { 'attributes' =>
                   { '_atom_site' => [ 'id' ],
                     '_struct_conn' => [ 'id' ] } } );

    my $atom_site = $pdbx_data->{'_atom_site'}{'data'};
    my $struct_conn = $pdbx_data->{'_struct_conn'}{'data'};

    # Assigns filters atoms and assigns to specified groups.
    my @group_ids =
        uniq( @{ filter( { 'atom_site' => $atom_site,
                           'data' => [ '[local]_selection_group' ],
                           'is_list' => 1 } ) } );

    my %atom_site_groups = ();
    for my $group_id ( @group_ids ) {
        if( ! exists $atom_site_groups{$group_id} ) {
            my $group_atom_site =
                filter( { 'atom_site' => $atom_site,
                          'include' =>
                              { '[local]_selection_state' => [ 'T' ],
                                '[local]_selection_group' => [ $group_id ] }});
            $atom_site_groups{$group_id} = $group_atom_site;
        } else {
            error( { 'program' => $0,
                     'message' => 'there are multiple instances of the group ' .
                                  "in different files.\n" } );
        }
    }

    # TODO: think what to do if the groups clash. Should queries overwrite?
    my %connections = ();
    for my $covalent_query ( split /;/, $covalent_queries) {
        my @group_ids = split /,/, $covalent_query;
        my $group_id1 = $group_ids[0];
        for my $group_id2 ( @group_ids[1..$#group_ids] ) {
            $connections{$group_id1}{$group_id2} = 'covale';
            $connections{$group_id2}{$group_id1} = 'covale';
        }
    }
    for my $disulfide_query ( split /;/, $disulfide_queries) {
        my @group_ids = split /,/, $disulfide_query;
        my $group_id1 = $group_ids[0];
        for my $group_id2 ( @group_ids[1..$#group_ids] ) {
            $connections{$group_id1}{$group_id2} = 'disulf';
            $connections{$group_id2}{$group_id1} = 'disulf';
        }
    }
    for my $hydrogen_query ( split /;/, $hydrogen_queries) {
        my @group_ids = split /,/, $hydrogen_query;
        my $group_id1 = $group_ids[0];
        for my $group_id2 ( @group_ids[1..$#group_ids] ) {
            $connections{$group_id1}{$group_id2} = 'hydrog';
            $connections{$group_id2}{$group_id1} = 'hydrog';
        }
    }
    for my $metalc_query ( split /;/, $metalc_queries) {
        my @group_ids = split /,/, $metalc_query;
        my $group_id1 = $group_ids[0];
        for my $group_id2 ( @group_ids[1..$#group_ids] ) {
            $connections{$group_id1}{$group_id2} = 'metalc';
            $connections{$group_id2}{$group_id1} = 'metalc';
        }
    }

    # TODO: might be useful to move to the separate function.
    my $counter = counter_struct_conn( $struct_conn );
    my %struct_conn_added = ();
    my %visited_connections = ();
    for my $group_id1 ( sort { $a <=> $b } keys %connections ) {
        next if ! defined $atom_site_groups{$group_id1};

        my ( $atom_id1 ) = keys %{ $atom_site_groups{$group_id1} };

        for my $group_id2 ( sort { $a <=> $b }
                            keys %{ $connections{$group_id1} } ) {
            next if $visited_connections{$group_id1}{$group_id2} ||
                $visited_connections{$group_id2}{$group_id1};

            $visited_connections{$group_id1}{$group_id2} = 1;
            $visited_connections{$group_id2}{$group_id1} = 1;

            next if ! defined $atom_site_groups{$group_id2};

            my $connection_type = $connections{$group_id1}{$group_id2};

            for my $atom_id2 ( sort { $a <=> $b }
                               keys %{ $atom_site_groups{$group_id2} } ) {
                if( $atom_site->{$atom_id1}{'group_PDB'} eq 'HETATM' &&
                    ( $atom_site->{$atom_id1}{'auth_asym_id'} eq '?' ||
                      $atom_site->{$atom_id1}{'auth_asym_id'} eq '.' ) &&
                    $atom_site->{$atom_id2}{'auth_asym_id'} ne '?' &&
                    $atom_site->{$atom_id2}{'auth_asym_id'} ne '.' ) {
                    my $residue_unique_key1 =
                        unique_residue_key( $atom_site->{$atom_id1} );
                    my $residue_atom_site1 =
                        filter_by_unique_residue_key( $atom_site,
                                                      $residue_unique_key1, 1 );
                    for my $residue_atom_id1 ( sort keys %{ $residue_atom_site1 } ) {
                        $atom_site->{$residue_atom_id1}{'auth_asym_id'} =
                            $atom_site->{$atom_id2}{'auth_asym_id'};
                    }
                }
                if( $atom_site->{$atom_id2}{'group_PDB'} eq 'HETATM' &&
                    ( $atom_site->{$atom_id2}{'auth_asym_id'} eq '?' ||
                      $atom_site->{$atom_id2}{'auth_asym_id'} eq '.' ) &&
                    $atom_site->{$atom_id1}{'auth_asym_id'} ne '?' &&
                    $atom_site->{$atom_id1}{'auth_asym_id'} ne '.' ) {
                    my $residue_unique_key2 =
                        unique_residue_key( $atom_site->{$atom_id2} );
                    my $residue_atom_site2 =
                        filter_by_unique_residue_key( $atom_site,
                                                      $residue_unique_key2, 1 );
                    for my $residue_atom_id2 ( sort keys %{ $residue_atom_site2 } ) {
                        $atom_site->{$residue_atom_id2}{'auth_asym_id'} =
                            $atom_site->{$atom_id1}{'auth_asym_id'};
                    }
                }

                %struct_conn_added = (
                    %struct_conn_added,
                    %{ create_struct_conn(
                           $atom_site->{$atom_id1},
                           $atom_site->{$atom_id2},
                           $connection_type,
                           $counter->{$connection_type} ) }
                );
                $counter->{$connection_type}++;
            }
        }
    }

    if( ! %{ $pdbx_data->{'_struct_conn'} } ) {
        $pdbx_data->{'_struct_conn'}{'data'} = clone \%struct_conn_added;
        $pdbx_data->{'_struct_conn'}{'metadata'}{'attributes'} = [
            'id', 'conn_type_id', 'ptnr1_label_seq_id', 'ptnr1_label_asym_id',
            'pdbx_ptnr1_label_alt_id', 'ptnr1_auth_seq_id', 'ptnr1_auth_asym_id',
            'ptnr1_label_atom_id', 'ptnr2_label_seq_id', 'ptnr2_label_asym_id',
            'ptnr2_auth_seq_id', 'pdbx_ptnr2_label_alt_id', 'ptnr2_auth_asym_id',
            'ptnr2_label_atom_id',
            ];
        $pdbx_data->{'_struct_conn'}{'metadata'}{'type'} = 'indexed';
        $pdbx_data->{'_struct_conn'}{'metadata'}{'is_loop'} = 1;
    } else {
        $pdbx_data->{'_struct_conn'}{'data'} = {
            %{ $pdbx_data->{'_struct_conn'}{'data'} },
            %struct_conn_added
        };
        $pdbx_data->{'_struct_conn'}{'metadata'}{'attributes'} = [
            'id', 'conn_type_id', 'ptnr1_label_seq_id', 'ptnr1_label_asym_id',
            'pdbx_ptnr1_label_alt_id', 'ptnr1_auth_seq_id', 'ptnr1_auth_asym_id',
            'ptnr1_label_atom_id', 'ptnr2_label_seq_id', 'ptnr2_label_asym_id',
            'ptnr2_auth_seq_id', 'pdbx_ptnr2_label_alt_id', 'ptnr2_auth_asym_id',
            'ptnr2_label_atom_id',
        ];
    }

    # Prints out cif or csv
    if( $output_format eq 'pdbx' ) {
        to_pdbx( $pdbx_data, { 'tags' => \@tags } );
    } elsif( $output_format eq 'csv' ) {
        if( scalar @tags == 1 ) {
            to_csv( $pdbx_data, { 'category' => $tags[0] } );
        } else {
            warning( { 'message' => "only one tag has to be chosen for " .
                           "CSV format.\n" } );
            exit;
        }
    } else {
        error( { 'program' => $0,
                 'message' => "output format '${output_format}'" .
                              " is not supported.\n" } );
    }
}
