#!/usr/bin/perl

use strict;
use warnings;

use autodie;
use File::Basename;
use Getopt::Long;
use Try::Tiny;

use ConnectAtoms qw( connect_atoms );
use ForceField::Parameters;
use Logging qw( error
                warning );
use Measure qw( all_bond_angles
                bond_angle );
use PDBxParser qw( filter
                   filter_by_unique_residue_key
                   mark_selection
                   obtain_pdbx_data
                   raw2indexed
                   to_csv
                   to_pdbx );
use Version qw( $VERSION );

Getopt::Long::Configure qw( gnu_getopt );

our $VERSION = $VERSION;

#*rotag_angle [options] [--] <cif-file>...
#*    calculates angles between selected atoms or bonds in residues.
#*
#*Usage:
#*    rotag_angle input.cif > output.cif
#*
#*Options:
#*    -S, --side-chains
#*                        calculates angles between bonds in the side-chain atoms.
#*    -M, --main-chains
#*                        calculates angles between bonds in the main-chain atoms.
#*    -r, --radians
#*                        angles are in radians.
#*    -F, --format <format>
#*                        output format (default: pdbx | csv).
#*    -v, --version
#*                        print version.

# --------------------------------- Options ----------------------------------- #

my $calc_sidechain = 0;
my $calc_mainchain = 0;
my $in_radians = 0;
my $output_format = 'pdbx';

local $SIG{__WARN__} = sub {
    warning( { 'program' => $0,
               'message' => @_,
               'filename' => join( ', ', @ARGV ) } );
};

local $SIG{__DIE__} = sub {
    error( { 'program' => $0,
             'message' => @_,
             'filename' => join( ', ', @ARGV ) } );
};

GetOptions(
    'side-chains|S' => sub { $calc_sidechain = 1 },
    'main-chains|M' => sub { $calc_mainchain = 1 },
    'radians|r' => sub { $in_radians = 1 },
    'format|F=s' => \$output_format,
    'help|h' => sub {
                        open my $fh, '<', $0;
                        while( <$fh> ) {
                            my ( $help_message ) = $_ =~ m/^#(\*.*)/;
                            if( $help_message ) {
                                $help_message =~ s/^\*$/ /smgx;
                                $help_message =~ s/^\*//smgx;
                                print $help_message, "\n";
                            }
                        }
                        close $fh;
                        exit;
                    },
    'version|v' => sub { print $VERSION, "\n"; exit; }
) or error( { 'program' => $0,
              'message' => "mistake in command line argument.\n" } );

# ----------------------------------- Main ------------------------------------ #

local @ARGV = ( q{-} ) unless @ARGV;

my $parameters = Parameters->new();
my $pi = $parameters->{'_[local]_constants'}{'pi'};
my $sig_figs_min = $parameters->{'_[local]_constants'}{'sig_figs_min'};
my $sig_figs_max = $parameters->{'_[local]_constants'}{'sig_figs_max'};

for my $pdbx_file ( @ARGV ) {
    my $pdbx = obtain_pdbx_data( $pdbx_file, [ '_atom_site' ] );
    raw2indexed( $pdbx, { 'attributes' => { '_atom_site' => [ 'id' ] } } );

    my $atom_site = $pdbx->{'_atom_site'}{'data'};

    if( ! defined $atom_site ) {
        warning( { 'program' => $0,
                   'message' => "no atom sites were detected.\n" } );
        next;
    }

    # Calculates distance between side-chain bonds.
    if( $calc_sidechain ) {
        $pdbx->{'_[local]_bond_angle'}{'metadata'}{'attributes'} =
            [ 'id', 'label_comp_id', 'label_seq_id', 'label_asym_id',
              'pdbx_PDB_model_num', 'label_alt_id', 'atom_1_id', 'label_atom_1_id',
              'atom_2_id', 'label_atom_2_id', 'atom_3_id', 'label_atom_3_id',
              'value', 'units' ];
        $pdbx->{'_[local]_bond_angle'}{'metadata'}{'is_loop'} = 1;
        $pdbx->{'_[local]_bond_angle'}{'metadata'}{'type'} = 'record';

        my $bond_angle_site =
            filter( { 'atom_site' => $atom_site,
                      'include' => { '[local]_selection_state' => [ 'T' ] } } );

        # Selects all atoms if no specific atoms are selected.
        if( ! %{ $bond_angle_site } ) {
            $bond_angle_site = $atom_site;
            mark_selection( $bond_angle_site,
                            { 'target' => [ keys %{ $bond_angle_site } ] } );
        }

        connect_atoms( $parameters, $bond_angle_site );

        my $bond_angles =
            all_bond_angles( $bond_angle_site,
                              {'calc_mainchain' => ( $calc_mainchain ? 1 : 0 )});

        my $bond_angle_id = 1;
        for my $residue_unique_key ( sort keys %{ $bond_angles } ) {
            my $residue_site =
                filter_by_unique_residue_key( $bond_angle_site,
                                              $residue_unique_key );
            my ( $residue_id ) = keys %{ $residue_site };
            my ( $label_seq_id, $chain_id, $model_id, $alt_id ) =
                split( /,/sxm, $residue_unique_key ),
            my $residue_name = $residue_site->{$residue_id}{'label_comp_id'};

            for my $first_atom_id (
                sort keys %{ $bond_angles->{$residue_unique_key} } ) {
                for my $second_atom_id (
                    sort keys %{ $bond_angles->{$residue_unique_key}
                                               {$first_atom_id} } ) {
                    for my $third_atom_id (
                        sort keys %{ $bond_angles->{$residue_unique_key}
                                                   {$first_atom_id}
                                                   {$second_atom_id} } ) {
                        push @{ $pdbx->{'_[local]_bond_angle'}{'data'} },
                        { 'id' => $bond_angle_id,
                          'label_comp_id' => $residue_name,
                          'label_seq_id' => $label_seq_id,
                          'label_asym_id' => $chain_id,
                          'pdbx_PDB_model_num' => $model_id,
                          'label_alt_id' => $alt_id,
                          'atom_1_id' => $first_atom_id,
                          'label_atom_1_id' =>
                              $bond_angle_site->{$first_atom_id}{'label_atom_id'},
                          'atom_2_id' => $second_atom_id,
                          'label_atom_2_id' =>
                              $bond_angle_site->{$second_atom_id}{'label_atom_id'},
                          'atom_3_id' => $third_atom_id,
                          'label_atom_3_id' =>
                              $bond_angle_site->{$third_atom_id}{'label_atom_id'},
                          'type' =>
                              $bond_angles->{$residue_unique_key}
                                            {$first_atom_id}
                                            {$second_atom_id}
                                            {$third_atom_id}{'type'},
                          'value' => ( $in_radians ?
                                       sprintf $sig_figs_max,
                                               $bond_angles->{$residue_unique_key}
                                                             {$first_atom_id}
                                                             {$second_atom_id}
                                                             {$second_atom_id}
                                                             {'value'} :
                                       sprintf $sig_figs_min,
                                               $bond_angles->{$residue_unique_key}
                                                             {$first_atom_id}
                                                             {$second_atom_id}
                                                             {$third_atom_id}
                                                             {'value'} * 180 / $pi ),
                          'units' => ( $in_radians ? 'radians': 'degrees' ) };
                        $bond_angle_id++;
                    }
                }
            }
        }

    } else {
        $pdbx->{'_[local]_angle'}{'metadata'}{'attributes'} =
            [ 'id', 'label_atom_1_id', 'atom_1_id', 'label_atom_2_id',
              'atom_2_id', 'label_atom_3_id', 'atom_3_id', 'value', 'units' ];
        $pdbx->{'_[local]_angle'}{'metadata'}{'is_loop'} = 1;
        $pdbx->{'_[local]_angle'}{'metadata'}{'type'} = 'record';

        my $angle_site =
            filter( { 'atom_site' => $atom_site,
                      'include' => { '[local]_selection_state' => [ 'T' ] },
                      'exclude' => { '[local]_selection_group' => [ q{?} ] } } );

        if( ! %{ $angle_site } ) {
            warning( { 'program' => $0,
                       'message' => 'no atoms were selected for calculating ' .
                                    "dihedral angles.\n" } );
            next;
        }

        my @angle_atom_ids =
            sort { $angle_site->{"$a"}{'[local]_selection_group'} <=>
                   $angle_site->{"$b"}{'[local]_selection_group'} ||
                   $angle_site->{"$a"}{'id'} <=>
                   $angle_site->{"$b"}{'id'}  }
            keys %{ $angle_site };

        my $angle_id = 1;
        for( my $i = 0; $i <= $#angle_atom_ids; $i = $i + 3 ) {
            my $first_atom_id = $angle_atom_ids[$i];
            my $second_atom_id = $angle_atom_ids[$i+1];
            my $third_atom_id = $angle_atom_ids[$i+2];
            my $angle =
                bond_angle(
                    [ map { [ $angle_site->{$_}{'Cartn_x'},
                              $angle_site->{$_}{'Cartn_y'},
                              $angle_site->{$_}{'Cartn_z'} ] }
                      ( $first_atom_id, $second_atom_id, $third_atom_id ) ] );

            push @{ $pdbx->{'_[local]_angle'}{'data'} },
                  { 'id' => $angle_id,
                    'label_atom_1_id' => $first_atom_id,
                    'atom_1_id' =>
                        $angle_site->{$first_atom_id}{'label_atom_id'},
                    'label_atom_2_id' => $second_atom_id,
                    'atom_2_id' =>
                        $angle_site->{$second_atom_id}{'label_atom_id'},
                    'label_atom_3_id' => $third_atom_id,
                    'atom_3_id' =>
                        $angle_site->{$third_atom_id}{'label_atom_id'},
                    'value' => ( $in_radians ?
                                 sprintf $sig_figs_max, $angle :
                                 sprintf $sig_figs_min, 180 * $angle / $pi ),
                    'units' => ( $in_radians ? 'radians': 'degrees' ) };

            $angle_id++;
        }
    }

    if( $output_format eq 'pdbx' ) {
        to_pdbx( $pdbx, { 'tags' => [ '_[local]_bond_angle',
                                      '_[local]_angle' ] } );
    } elsif( $output_format eq 'csv' ) {
        # TODO: extend to '_[local]_length'.
        to_csv( $pdbx, { 'category' => '_[local]_bond_angle' } );
    } else {
        error(
            { 'program' => $0,
              'message' => "output format '${output_format}'" .
                           " is not supported.\n" } );
    }
}
