#!/usr/bin/perl

use strict;
use warnings;

use autodie;
use Getopt::Long;

use ForceField::Parameters();
use ForceField::Bonded qw( general );
use ForceField::NonBonded qw( general );
use Logging qw( error
                warning );
use PDBxParser qw( filter
                   obtain_pdbx_data
                   raw2indexed
                   record2raw
                   split_by
                   to_csv
                   to_pdbx );
use SidechainInteractions;
use Version qw( $VERSION );

Getopt::Long::Configure qw( gnu_getopt );

our $VERSION = $VERSION;

#*rotag_predict [options] --side-chains [--] <cif-file>...
#*    predict side-chain positions.
#*
#*Usage:
#*    rotag_predict --side-chains input.cif > output.cif
#*
#*Options:
#*    -S, --side-chains
#*                        predicts all probable side-chain positions according to
#*                        the given energy threshold.
#*    --tags <tag>[,<tag>...]
#*                        select PDBx categories that will be in the output
#*                        (default: '_atom_site,_[local]_rotamer_angle,_[local]_rotamer_energy,_[local]_pairwise_energy').
#*    --dry-run
#*                        runs without calculating pairwise interactions, but
#*                        goes through all the necessary steps.
#*    --graphs-csv
#*                        prints out graph data in CSV format.
#*    -F, --format <format>
#*                        output format. Only one category can be present if csv
#*                        is select (default: pdbx | csv).
#*    --verbose
#*                        print out additional information about the updated
#*                        count of conformations.
#*    -v, --version
#*                        prints version.

# --------------------------------- Options ----------------------------------- #

my $predict_sidechains = 0;
my $tags =
    '_atom_site,_[local]_rotamer_angle,_[local]_rotamer_energy,_[local]_pairwise_energy';
my $graphs_csv = 0;
my $dry_run = 0;
my $verbose = 0;
my $output_format = 'pdbx';
my @category_list =
    ( '_atom_site', '_[local]_rotamer_angle', '_[local]_rotamer_energy' );
my @attribute_list =
    ( 'label_seq_id', 'label_comp_id', 'label_entity_id', 'label_alt_id',
      'rotamer_id', 'type', 'value', );

local $SIG{__WARN__} = sub {
    warning( { 'program' => $0, 'message' => @_ } );
};

local $SIG{__DIE__} = sub {
    error( { 'program' => $0, 'message' => @_ } );
};

GetOptions(
    'side-chains|S' => sub { $predict_sidechains = 1 },
    'tags=s' => \$tags,
    'graphs-csv' => sub { $graphs_csv = 1 },
    'dry-run' => sub { $dry_run = 1 },
    'format|F=s' => \$output_format,
    'verbose' => sub { $verbose = 1 },
    'help|h' => sub {
                        open my $fh, '<', $0;
                        while( <$fh> ) {
                            my ( $help_message ) = $_ =~ m/^#(\*.*)/;
                            if( $help_message ) {
                                $help_message =~ s/^\*$/ /smgx;
                                $help_message =~ s/^\*//smgx;
                                print $help_message, "\n";
                            }
                        }
                        close $fh;
                        exit;
                    },
    'version|v' => sub { print $VERSION, "\n"; exit; }
) or error( { 'program' => $0,
              'message' => "mistake in command line argument.\n" } );

# ----------------------------------- Main ------------------------------------ #

local @ARGV = ( q{-} ) unless @ARGV;

$tags =~ s/ //g;
my @tags = split /,/, $tags;

my $parameters = Parameters->new();
my $pi = $parameters->{'_[local]_constants'}{'pi'};
my $interaction_atom_names = $parameters->{'_[local]_interaction_atom_names'};

for my $pdbx_file ( @ARGV ) {
    my $pdbx_data = obtain_pdbx_data( $pdbx_file, \@category_list );
    raw2indexed( $pdbx_data,
                 { 'attributes' => { '_atom_site' => [ 'id' ],
                                     '_[local]_rotamer_angle' => [ 'id' ],
                                     '_[local]_rotamer_energy' => [ 'id' ] } });

    # Reads file path, stdin and '-' operator.
    my $atom_site = $pdbx_data->{'_atom_site'}{'data'};

    if( ! defined $atom_site ) {
        warning( { 'program' => $0,
                   'message' => "no atom sites were detected.\n" } );
        next;
    }

    my $selected_atom_site =
        filter( { 'atom_site' => $atom_site,
                  'include' => { '[local]_selection_state' => [ 'T', 'S' ] } } );
    my $target_atom_site =
        filter( { 'atom_site' => $selected_atom_site,
                  'include' => { '[local]_selection_state' => [ 'T' ] } } );
    my $target_atom_ids =
        filter( { 'atom_site' => $target_atom_site,
                  'include' => { '[local]_selection_state' => [ 'T' ] },
                  'exclude' => { 'label_atom_id' => $interaction_atom_names },
                  'data' => [ 'id' ],
                  'is_list' => 1 } );

    if( $predict_sidechains ) {
        my $rotamer_angles = $pdbx_data->{'_[local]_rotamer_angle'}{'data'};
        my $rotamer_energies = $pdbx_data->{'_[local]_rotamer_energy'}{'data'};

        if( ! defined $rotamer_angles ) {
            warning( { 'program' => $0,
                       'message' => "no rotamer angles were detected.\n" } );
            next;
        }

        my $sidechain_interactions = SidechainInteractions->new(
            $parameters, $atom_site, $rotamer_angles, $rotamer_energies
        );

        $sidechain_interactions->predict( {
            'non_bonded_potential' => \&ForceField::NonBonded::general,
            'program_called_by' => $0,
            'dry_run' => $dry_run,
            'verbose' => $verbose,
        } );

        my $pairwise_rotamer_energies =
            $sidechain_interactions->get_pairwise_rotamer_energies();

        if( exists $pairwise_rotamer_energies->{'_[local]_pairwise_energy'}
                                               {'data'} ) {
            $pdbx_data->{'_[local]_pairwise_energy'} =
                $pairwise_rotamer_energies->{'_[local]_pairwise_energy'};
        }

        if( $graphs_csv ) {
            my %rotamer_to_unique_residue_key = ();
            for my $rotamer_angle_id ( keys %{ $rotamer_angles } ) {
                my $rotamer_angle = $rotamer_angles->{$rotamer_angle_id};
                my $rotamer_id = $rotamer_angle->{'rotamer_id'};
                my $unique_residue_key =
                    sprintf '%s,%s,%s,%s',
                    $rotamer_angle->{'label_seq_id'},
                    $rotamer_angle->{'label_asym_id'},
                    $rotamer_angle->{'pdbx_PDB_model_num'},
                    $rotamer_angle->{'label_alt_id'};
                $rotamer_to_unique_residue_key{$rotamer_id} =
                    $unique_residue_key;
            }

            my %visited_pairwise_rotamer_ids = ();
            for my $pairwise_energy (
                @{ $pairwise_rotamer_energies->{'_[local]_pairwise_energy'}
                                               {'data'} } ) {
                my ( $unique_residue_key_1, $unique_residue_key_2 ) =
                    map { $rotamer_to_unique_residue_key{$_} }
                        ( $pairwise_energy->{'rotamer_id_1'},
                          $pairwise_energy->{'rotamer_id_2'} );
                if( ! ( exists $visited_pairwise_rotamer_ids{$unique_residue_key_1}
                                                            {$unique_residue_key_2} ||
                        exists $visited_pairwise_rotamer_ids{$unique_residue_key_2}
                                                            {$unique_residue_key_1} ) ) {
                    $visited_pairwise_rotamer_ids{$unique_residue_key_1}
                                                 {$unique_residue_key_2} = 1;
                    printf "\"%s\",\"%s\"\n",
                        $unique_residue_key_1,
                        $unique_residue_key_2;
                }
            }
        } elsif( $output_format eq 'pdbx' ) {
            to_pdbx( $pdbx_data, { 'tags' => \@tags } );
        } elsif( $output_format eq 'csv' ) {
            if( scalar @tags == 1 ) {
                to_csv( $pdbx_data, { 'category' => $tags[0] } );
            } else {
                warning( { 'program' => $0,
                           'message' => "only one tag has to be chosen for " .
                                        "CSV format.\n" } );
                exit;
            }
        }
    } else {
        error(
            { 'program' => $0,
              'filename' => $pdbx_file,
              'message' => "no options were chosen for atom additions.\n" } );
    }
}
