#!/usr/bin/perl

use strict;
use warnings;

use autodie;
use Carp;
use Getopt::Long;
use Try::Tiny;

use Logging qw( error
                warning );
use PDBxParser qw( obtain_pdbx_data
                   raw2indexed
                   to_pdbx
                   to_csv );
use Version qw( $VERSION );

Getopt::Long::Configure qw( gnu_getopt );

our $VERSION = $VERSION;

#*rotag_connect [options] (--covale|--disulf|--hydrog|--metalc) \
#*    <groups-to-connect> [--] <cif-file>...
#*    connects and/or marks interactions between atoms of two or more atom
#*    groups by adding '_struct_conn' loop entries.
#*
#*Usage:
#*    rotag_connect --metalc '1,2' input.cif > output.cif
#*    rotag_connect --covale '1,2;3,4' input.cif > output.cif
#*    rotag_connect --metalc '1,2' --hydrog '4,5' input.cif > output.cif
#*
#*Options:
#*    --covale <group>,<group>[;<group>,<group>;...]
#*                        connects atoms by covalent bond.
#*    --disulf <group>,<group>[;<group>,<group>;...]
#*                        connects atoms by disulfide bond.
#*    --hydrog <group>,<group>[;<group>,<group>;...]
#*                        marks atoms participating in hydrogen bond.
#*    --metalc <group>,<group>[;<group>,<group>;...]
#*                        marks atoms participating in metal coordination.
#*    --tags <tag>[,<tag>...]
#*                        select PDBx categories that will be in the output
#*                        (default: '_atom_site,_struct_conn').
#*    -F, --format <format>
#*                        output format (default: pdbx | csv).
#*    -v, --version
#*                        print version.

# --------------------------------- Options ----------------------------------- #

my $covalent_query = '';
my $disulfide_query = '';
my $hydrogen_query = '';
my $metalc_query = '';
my $tags = '_atom_site,_struct_conn';
my $output_format = 'pdbx';
my @category_list = ( '_atom_site', '_struct_conn' );

local $SIG{__WARN__} = sub {
    warning( { 'program' => $0,
               'message' => @_,
               'filename' => join( ', ', @ARGV ) } );
};

local $SIG{__DIE__} = sub {
    error( { 'program' => $0,
             'message' => @_,
             'filename' => join( ', ', @ARGV ) } );
};

GetOptions(
    'covale=s' => \$covalent_query,
    'disulf=s' => \$disulfide_query,
    'hydrog=s' => \$hydrogen_query,
    'metalc=s' => \$metalc_query,
    'tags=s' => \$tags,
    'format|F=s' => \$output_format,
    'help|h' => sub {
                        open my $fh, '<', $0;
                        while( <$fh> ) {
                            my ( $help_message ) = $_ =~ m/^#(\*.*)/;
                            if( $help_message ) {
                                $help_message =~ s/^\*$/ /smgx;
                                $help_message =~ s/^\*//smgx;
                                print $help_message, "\n";
                            }
                        }
                        close $fh;
                        exit;
                    },
    'version|v' => sub { print $VERSION, "\n"; exit; }
)  or error( { 'program' => $0,
               'message' => "mistake in command line argument.\n" } );

# ----------------------------------- Main ------------------------------------ #

local @ARGV = ( q{-} ) unless @ARGV;

$tags =~ s/ //g;
my @tags = split /,/, $tags;

my %atom_site_groups = ();

for my $pdbx_file ( @ARGV ) {
    my $pdbx_data = obtain_pdbx_data( $pdbx_file, \@category_list );

    if( ! defined $pdbx_data->{'_atom_site'}{'data'} ) {
        warning( { 'program' => $0,
                   'message' => "no atom sites were detected.\n" } );
        next;
    }

    raw2indexed( $pdbx_data,
                 { 'attributes' =>
                   { '_atom_site' => [ 'id' ],
                     '_struct_conn' => [ 'id' ] } } );

    my $atom_site = $pdbx_data->{'_atom_site'}{'data'};
    my $struct_conn = $pdbx_data->{'_struct_conn'}{'data'};
}

# # Prints out cif or csv
# # TODO: decide what to do when group data is empty.
# if( $output_format eq 'pdbx' ) {
#     to_pdbx( \%pdbx_data, { 'tags' => \@tags } );
# } elsif( $output_format eq 'csv' ) {
#     if( scalar @tags == 1 ) {
#         to_csv( \%pdbx_data, { 'category' => $tags[0] } );
#     } else {
#         warning( { 'message' => "only one tag has to be chosen for " .
#                        "CSV format.\n" } );
#         exit;
#     }
# } else {
#     error( { 'program' => $0,
#              'message' => "output format '${output_format}'" .
#                           " is not supported.\n" } );
# }
