#!/bin/bash

#
# Runs simple Maxima one-liners.
#

# Runs Maxima in quiet mode, removes "done" warning that is produce during
# initiation of fortran function and removes whitespaces, because
# Maxima is whitespace-sensitive when it comes to input.
echo $1 \
    | sed 's/\s//g' \
    | maxima --very-quiet \
    | grep -v 'done' \
    | sed 's/\s//g'
