#!/usr/bin/perl

use strict;
use warnings;

use Moieties qw( %ATOMS );
use PDBxParser qw( to_pdbx );
use PseudoAtoms qw( add_moiety );

my ( $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );
add_moiety( $atom_site, $ATOMS{'H'}, 155, 158, 1 );
# %{ $atom_site } =
#     ( %{ $atom_site },
#       %{ add_hydrogens( $atom_site ) } );

# # Prints out PDBx format file.
# to_pdbx( { "atom_site" => $atom_site } );
