#!/usr/bin/perl

use strict;
use warnings;

use ForceField::Parameters;
use Hydrogens qw( add_hydrogens );
use PDBxParser qw( to_pdbx );

my ( $pdbx_dump_file, $add_only_clear_positions ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $parameters = Parameters->new();

%{ $atom_site } =
    ( %{ $atom_site },
      %{ add_hydrogens(
             $parameters,
             $atom_site,
             { 'add_only_clear_positions' => $add_only_clear_positions } ) } );

# Prints out PDBx format file.
to_pdbx( { "pdbx_data_indexed" => { '_atom_site' => $atom_site } } );
