#!/usr/bin/perl

use strict;
use warnings;

use ForceField::Parameters;
use PDBxParser qw( to_pdbx );
use PseudoAtoms qw( add_hydrogens );

my ( $pdbx_dump_file, $add_only_clear_positions ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $PARAMETERS = Parameters->new();

%{ $atom_site } =
    ( %{ $atom_site },
      %{ add_hydrogens(
             $atom_site,
             $PARAMETERS,
             { 'add_only_clear_positions' => $add_only_clear_positions } ) } );

# Prints out PDBx format file.
to_pdbx( { "atom_site" => $atom_site } );
