#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;

use AlterMolecule qw( angle_bending );
use ForceField::Parameters;

$Data::Dumper::Indent = 1;
$Data::Dumper::Sortkeys = 1;

#
# Unit test: AlterMolecule::angle_bending.
# Example: ./angle_bending atom-coords.dat
#

my ( $atom_coords_file ) = @ARGV;

my @atom_coords;
open( my $fh, "<", $atom_coords_file );
while( <$fh> ){
    push( @atom_coords, [ grep( /\S/, split( /#.+|\s+/, $_ ) ) ] );
}
close( $fh );

my $parameters = Parameters->new();

my $angle_bending_matrix =
    angle_bending( $parameters,
                   $atom_coords[0],
                   $atom_coords[1],
                   $atom_coords[2],
                   "psi",
                   "theta" );

print Dumper $angle_bending_matrix;
