#!/usr/bin/perl

use strict;
use warnings;

use AlterMolecule qw( angle_bending );

#
# Unit test: AlterMolecule::angle_bending.
# Example: ./angle_bending atom-coords.dat
#

my ( $atom_coords_file ) = @ARGV;

my @atom_coords;
open( my $fh, "<", $atom_coords_file );
while( <$fh> ){
    push( @atom_coords, [ grep( /\S/, split( /#.+|\s+/, $_ ) ) ] );
}
close( $fh );

my $angle_bending_matrix =
    angle_bending( $atom_coords[0],
                   $atom_coords[1],
                   $atom_coords[2],
                   "psi",
                   "theta" );

for my $matrix_id ( 0..$#{ $angle_bending_matrix } ) {
    for my $row ( @{ $angle_bending_matrix->[$matrix_id] } ) {
        print( join( "\t", @{ $row } ), "\n" );
    }
    print( "\n" ) if $matrix_id != $#{ $angle_bending_matrix };
}
