#!/usr/bin/perl

use strict;
use warnings;

use ForceField::Parameters;
use PDBxParser qw( to_pdbx );
use Measure qw( around_distance );

#
# Unit test: Measure::around_distance.
# Example: ./around_distance "label_atom_id CA,N,CB,OG" \
#                            5 \
#                            structure.dump
#

@ARGV = ( "-" ) unless @ARGV;
my ( $include_specifier,
     $around_distance,
     $pdbx_dump_file ) = @ARGV;

my %include_specifier = ( map { $_->[0] => [ split( ",", @$_[1] ) ] }
                          map { [ split( " ", $_ ) ] }
                          split( "&", $include_specifier ) );

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $parameters = Parameters->new();


# Prints out PDBx format file.
my %pdbx =();
$pdbx{'_atom_site'}{'data'} = around_distance( $parameters,
                                               $atom_site,
                                               \%include_specifier,
                                               $around_distance );
$pdbx{'_atom_site'}{'metadata'}{'is_loop'} = 1;
$pdbx{'_atom_site'}{'metadata'}{'type'} = 'indexed';

to_pdbx( \%pdbx );
