#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;

use AlterMolecule qw( bond_torsion );

$Data::Dumper::Indent = 1;
$Data::Dumper::Sortkeys = 1;

#
# Unit test: AlterMolecule::bond_torsion.
# Example: ./bond_torsion atom-coords.dat
#

my ( $atom_coords_file ) = @ARGV;

my @atom_coords;
open( my $fh, "<", $atom_coords_file );
while( <$fh> ){
    push( @atom_coords, [ grep( /\S/, split( /#.+|\s+/, $_ ) ) ] );
}
close( $fh );

my $bond_torsion_matrix =
    bond_torsion( $atom_coords[0], $atom_coords[1], $atom_coords[2], "chi");

print Dumper $bond_torsion_matrix;
