#!/usr/bin/perl

use strict;
use warnings;

use AlterMolecule qw( bond_torsion );

#
# Unit test: AlterMolecule::bond_torsion.
# Example: ./bond_torsion atom-coords.dat
#

my ( $atom_coords_file ) = @ARGV;

my @atom_coords;
open( my $fh, "<", $atom_coords_file );
while( <$fh> ){
    push( @atom_coords, [ grep( /\S/, split( /#.+|\s+/, $_ ) ) ] );
}
close( $fh );

my $bond_torsion_matrix =
    bond_torsion( $atom_coords[0], $atom_coords[1], $atom_coords[2], "chi");

for my $matrix_id ( 0..$#{ $bond_torsion_matrix } ) {
    for my $row ( @{ $bond_torsion_matrix->[$matrix_id] } ) {
	print( join( "\t", @{ $row } ), "\n" );
    }
    print( "\n" ) if $matrix_id != $#{ $bond_torsion_matrix };
}
