#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;

use AlterMolecule qw( bond_stretching );
use ForceField::Parameters;

$Data::Dumper::Indent = 1;
$Data::Dumper::Sortkeys = 1;

#
# Unit test: AlterMolecule::bond_stretching.
# Example: ./bond_stretching atom-coords.dat
#

my ( $atom_coords_file ) = @ARGV;

my @atom_coords;
open( my $fh, "<", $atom_coords_file );
while( <$fh> ){
    push( @atom_coords, [ grep( /\S/, split( /#.+|\s+/, $_ ) ) ] );
}
close( $fh );

my $PARAMETERS = Parameters->new();

my $bond_stretching_matrix =
    bond_stretching( $atom_coords[0], $atom_coords[1], $atom_coords[2], "r",
                     $PARAMETERS );

print Dumper $bond_stretching_matrix;
