#!/usr/bin/perl

use strict;
use warnings;

use Constants qw( $SIG_FIGS );
use Measure qw( bond_angle );

#
# Unit test: Measure::bond_angle
# Example: ./bond_angle atom-coords.dat
#

my ( $atom_coords_file ) = @ARGV;

my @atom_coords;
open( my $fh, "<", $atom_coords_file );
while( <$fh> ){
    push( @atom_coords, [ grep( /\S/, split( /#.+|\s+/, $_ ) ) ] );
}
close( $fh );

printf( "$SIG_FIGS\n", bond_angle( \@atom_coords ) );
