#!/usr/bin/perl

use strict;
use warnings;

use Constants qw( $SIG_FIGS_MIN );
use Measure qw( bond_length );

#
# Unit test: Measure::bond_length
# Example: ./bond_length atom-coords.dat
#

my ( $atom_coords_file ) = @ARGV;

my @atom_coords;
open( my $fh, "<", $atom_coords_file );
while( <$fh> ){
    push( @atom_coords, [ grep( /\S/, split( /#.+|\s+/, $_ ) ) ] );
}
close( $fh );

printf( "$SIG_FIGS_MIN\n", bond_length( \@atom_coords ) );
