#!/usr/bin/perl

use strict;
use warnings;

use BondParameters;
use ForceField::Parameters;

#
# Unit test: BondParameters->calculate_dihedral_angles()
# Example: ./BondParameters_calculate_dihedral_angles structure.dump 1
#

my ( $pdbx_dump_file, $include_mainchain ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $PARAMETERS = Parameters->new();
my $pi = $PARAMETERS->{'_[local]_constants'}{'pi'};
my $bond_parameters = BondParameters->new(
    $PARAMETERS, $atom_site, { 'include_mainchain' => $include_mainchain }
);

$bond_parameters->calculate_dihedral_angles();

for my $residue_unique_key ( sort @{ $bond_parameters->get_unique_residue_keys } ) {
    for my $angle_name ( sort { $a cmp $b }
                    keys %{ $bond_parameters->get_dihedral_angles( $residue_unique_key ) } ) {
        print( join( " ", split( ",", $residue_unique_key ), $angle_name ), " " );
        printf( "%.1f\n",
                $bond_parameters->get_dihedral_angle_value(
                    $residue_unique_key, $angle_name
                ) * 180 /
                $pi );
    }
}
