#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;

use BondPath;

$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Indent = 1;

#
# Unit test: BondPath
# Example: ./bond_path structure.dump
#

my ( $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $bond_path = BondPath->new( { 'atom_site' => $atom_site } );

print Dumper $bond_path;
