#!/usr/bin/perl

use strict;
use warnings;

use BondParameters;
use ForceField::Parameters;

#
# Unit test: BondParameters->calculate_dihedral_angles()
# Example: ./BondParameters_calculate_dihedral_angles structure.dump 1
#

my ( $pdbx_dump_file, $include_mainchain ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $PARAMETERS = Parameters->new();
my $pi = $PARAMETERS->{'_[local]_constants'}{'pi'};
my $bond_parameters = BondParameters->new(
    $PARAMETERS, $atom_site, { 'include_mainchain' => $include_mainchain }
);

$bond_parameters->set_rotatable_bonds();
$bond_parameters->calculate_dihedral_angles();
# my $dihedral_angles = all_dihedral(
#     $parameters, $atom_site, { 'include_mainchain' => $include_mainchain }
# )->{'dihedral_angles'}{'residue_unique_key'};

# for my $residue_unique_key ( sort keys %{ $dihedral_angles } ) {
#     for my $angle ( sort { $a cmp $b }
#                     keys %{ $dihedral_angles->{$residue_unique_key} } ) {
#         print( join( " ", split( ",", $residue_unique_key ), $angle ), " " );
#         printf( "%.1f\n",
#                 $dihedral_angles->{$residue_unique_key}{$angle}{'value'} * 180 /
#                 $pi );
#     }
# }
