#!/usr/bin/perl

use strict;
use warnings;

use ForceField::Parameters;
use Measure qw( bond_angle );

#
# Unit test: Measure::bond_angle
# Example: ./bond_angle atom-coords.dat
#

my ( $atom_coords_file ) = @ARGV;

my @atom_coords;
open( my $fh, "<", $atom_coords_file );
while( <$fh> ){
    push( @atom_coords, [ grep( /\S/, split( /#.+|\s+/, $_ ) ) ] );
}
close( $fh );

my $PARAMETERS = Parameters->new();
my $SIG_FIGS_MIN = $PARAMETERS->{'_[local]_constants'}{'sig_figs_min'};

printf( "$SIG_FIGS_MIN\n", bond_angle( \@atom_coords ) );
