#!/usr/bin/perl

use strict;
use warnings;

use PDBxParser qw( to_pdbx );
use AlterMolecule qw( bond_positioning );
use Data::Dumper;
my ( $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

print Dumper bond_positioning( 'mid_atom_coord' => [ -54.128, -110.543, -6.071 ],
                  'up_atom_coord' => [ -54.506, -111.705, -5.149 ],
                  'right_atom_coord' => [ -53.415, -111.063, -7.316 ],
                  'left_atom_coord' => [ -55.320, -109.795, -6.452 ],
                  'back_atom_coord' => undef,
                  'add' => 'back_atom_coord',
                  'bond_length' => 1 );

# %{ $atom_site } =
#     ( %{ $atom_site },
#       %{ add_hydrogens( $atom_site ) } );

# # Prints out PDBx format file.
# to_pdbx( { "atom_site" => $atom_site } );
