#!/usr/bin/perl

use strict;
use warnings;

use BondParameters;
use ForceField::Parameters;

#
# Unit test: BondParameters->find_rotatable_bonds()
# Example: ./BondParameters_find_rotatable_bonds structure.dump
#

my ( $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $parameters = Parameters->new();
my $bond_parameters = BondParameters->new( $parameters, $atom_site );

$bond_parameters->find_rotatable_bonds();
my $rotatable_bonds = $bond_parameters->rotatable_bonds;

for my $atom_id ( sort { $a cmp $b } keys %{ $rotatable_bonds } ) {
    print( "$atom_site->{$atom_id}{\"label_atom_id\"}: "  );
    for my $angle ( sort { $rotatable_bonds->{$atom_id}{$a}{'order'} <=>
                           $rotatable_bonds->{$atom_id}{$b}{'order'} }
                    keys %{ $rotatable_bonds->{$atom_id} } ) {
        my $first_atom_id = $rotatable_bonds->{$atom_id}{$angle}{'atom_ids'}[1];
        my $second_atom_id = $rotatable_bonds->{$atom_id}{$angle}{'atom_ids'}[2];
        print( "$atom_site->{$first_atom_id}{\"label_atom_id\"}," .
               "$atom_site->{$second_atom_id}{\"label_atom_id\"} " );
    }
    print( "\n" );
}
