#!/usr/bin/perl

use strict;
use warnings;

use BondParameters;
use ForceField::Parameters;

#
# Unit test: BondParameters->find_bendable_angles()
# Example: ./BondParameters_find_bendable_angles structure.dump
#

my ( $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $parameters = Parameters->new();
my $bond_parameters = BondParameters->new( $parameters, $atom_site );

$bond_parameters->find_bendable_angles();
my $bendable_angles = $bond_parameters->bendable_angles;

for my $atom_id ( sort { $a cmp $b } keys %{ $bendable_angles } ) {
    print( "$atom_site->{$atom_id}{\"label_atom_id\"}: "  );
    for my $angle ( sort { $bendable_angles->{$atom_id}{$a}{'order'} <=>
                           $bendable_angles->{$atom_id}{$b}{'order'} }
                    keys %{ $bendable_angles->{$atom_id} } ) {
        my $first_atom_id  = $bendable_angles->{$atom_id}{$angle}{'atom_ids'}[0];
        my $second_atom_id = $bendable_angles->{$atom_id}{$angle}{'atom_ids'}[1];
        my $third_atom_id  = $bendable_angles->{$atom_id}{$angle}{'atom_ids'}[2];
        print( "$atom_site->{$first_atom_id}{\"label_atom_id\"}," .
               "$atom_site->{$second_atom_id}{\"label_atom_id\"}," .
               "$atom_site->{$third_atom_id}{\"label_atom_id\"} " );
    }
    print( "\n" );
}
