#!/usr/bin/perl

use strict;
use warnings;

use BondParameters;
use ForceField::Parameters;

#
# Unit test: BondParameters->calculate_bond_lengths()
# Example: ./BondParameters_calculate_bond_lengths structure.dump 1
#

my ( $pdbx_dump_file, $include_mainchain ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $PARAMETERS = Parameters->new();
my $pi = $PARAMETERS->{'_[local]_constants'}{'pi'};
my $bond_parameters = BondParameters->new(
    $PARAMETERS, $atom_site, { 'include_mainchain' => $include_mainchain }
);

$bond_parameters->calculate_bond_lengths();
my $bond_lengths = $bond_parameters->bond_lengths;

for my $residue_unique_key ( sort keys %{ $bond_lengths } ) {
    for my $bond_name ( sort { $a cmp $b }
                        keys %{ $bond_lengths->{$residue_unique_key} } ) {
        print( join( " ", split( ",", $residue_unique_key ), $bond_name ), " " );
        printf( "%.1f\n",
                $bond_lengths->{$residue_unique_key}{$bond_name}{'value'} * 180 /
                $pi );
    }
}
