#!/usr/bin/perl

use strict;
use warnings;

use AtomInteractions qw( hard_sphere );
use Constants qw( $PI
                  $SIG_FIGS );
use PDBxParser qw( filter
                   to_pdbx );
use PseudoAtoms qw( calc_favourable_angles );

my ( $residue_id,
     $residue_chain,
     $pdbx_model,
     $residue_alt,
     $small_angle,
     $potential,
     $interaction_specifier,
     $energy_cutoff_atom,
     $energy_cutoff_residue,
     $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

$small_angle =~ s/pi/\$PI/g;

my %interaction_specifier = ( map { $_->[0] => [ split( ",", @$_[1] ) ] }
                              map { [ split( " ", $_ ) ] }
                              split( "&", $interaction_specifier ) );
my $interaction_site = filter( { 'atom_site' => $atom_site,
                                 'include' => \%interaction_specifier } );

my $favourable_angles =
    calc_favourable_angles( { 'atom_site' => $atom_site,
                              'residue_unique_key' =>
                                  "${residue_id},${residue_chain},".
                                  "${pdbx_model},${residue_alt}",
                              'interaction_site' => $interaction_site,
                              'small_angle' => eval( $small_angle ),
                              'potential_function' => \&hard_sphere,
                              'energy_cutoff_atom' => $energy_cutoff_atom,
                              'threads' => 1,
                            } );

my $angle_id = 1;
for my $angles ( @{ $favourable_angles } ) {
    my @angle_names = map { "chi${_}" } 1..$#{ $angles }+1;
    for my $i ( 0..$#{ $angles } ) {
        print $angle_id, ', ', $angle_names[$i], ', ',
            sprintf( $SIG_FIGS, 180 * $angles->[$i] / $PI ), "\n";
    }
    $angle_id++;
}
