#!/usr/bin/perl

use strict;
use warnings;

use PDBxParser qw( filter
                   to_pdbx );
use Grammar::CommandLineParser;

#
# Unit test: Grammar::CommandLineParser.
# Example: ./command_line_parser 'resname ASP & atoname CA' structure.dump
#

@ARGV = ( "-" ) unless @ARGV;
my ( $selection_command,
     $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $command_line_parser = new CommandLineParser();
my $selected_atom_site = $command_line_parser->parser( $atom_site,
						       $selection_command,
						       "id" );

to_pdbx( $selected_atom_site );
