#!/usr/bin/perl

use strict;
use warnings;

use ForceField::Interactions::Composite qw( general );

my ( $atom_i_id, $atom_j_id, $pdbx_dump_file, $parameters ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

$parameters =~ s/\s//g;
$parameters = {
    map { $_->[0] => $_->[1] }
    map { [ split /=/sm, $_ ] }
    split /,/sxm, $parameters
};
$parameters->{'atom_site'} = $atom_site;

print general( $atom_site->{$atom_i_id},
               $atom_site->{$atom_j_id},
               $parameters ), "\n";
