#!/usr/bin/perl

use strict;
use warnings;

use ForceField::NonBonded qw( general );
use ForceField::Parameters;

my ( $atom_i_id, $atom_j_id, $pdbx_dump_file, $parameters ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

$parameters =~ s/\s//g;
my $PARAMETERS = Parameters->new();
$PARAMETERS->set_parameter_values(
    { '_[local]_constants' =>
      { map { ( split /=/sm, $_ ) } split /,/sxm, $parameters } }
);

my %options;
$options{'atom_site'} = $atom_site;

print general( $atom_site->{$atom_i_id},
               $atom_site->{$atom_j_id},
               $PARAMETERS,
               \%options ), "\n";
