#!/usr/bin/perl

use strict;
use warnings;

use ForceField::NonBonded qw( general );
use ForceField::Parameters;

my ( $atom_i_id, $atom_j_id, $pdbx_dump_file, $parameters_cmd ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

$parameters_cmd =~ s/\s//g;
my $parameters = Parameters->new();
$parameters->set_parameter_values(
    { '_[local]_force_field' =>
          { map { ( split /=/sm, $_ ) } split /,/sxm, $parameters_cmd } }
);

my %options;
$options{'atom_site'} = $atom_site;

print general( $parameters,
               $atom_site->{$atom_i_id},
               $atom_site->{$atom_j_id},
               \%options ), "\n";
