#!/usr/bin/perl

use strict;
use warnings;

use ConnectAtoms qw( connect_atoms_explicitly );
use ForceField::Parameters;

#
# Unit test: ConnectAtoms::connect_atoms_explicitly
# Example: ./connect_atoms_explicitly 1,2,3 4 structure.dump
#

my ( $first_atom_id_list, $second_atom_id_list, $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

connect_atoms_explicitly( $atom_site,
                          [ split ',', $first_atom_id_list ],
                          [ split ',', $second_atom_id_list ] );

my @atom_coord;
my @parent_atom;
my @child_atom;

for my $parent_id ( keys %{ $atom_site } ) {
    @parent_atom = ( $parent_id, $atom_site->{$parent_id}{"label_atom_id"} );
    for my $child_id ( @{ $atom_site->{$parent_id}{"connections"} } ) {
        @child_atom = ( $child_id, $atom_site->{$child_id}{"label_atom_id"} );
        print( "$parent_atom[0] $parent_atom[1]:" );
        print( "$child_atom[0] $child_atom[1]\n" );
    }
}
