#!/usr/bin/perl

use strict;
use warnings;

use ConnectAtoms qw( connection_digest );
use ForceField::Parameters;

#
# Unit test: ConnectAtoms::connection_digest
# Example: ./connection_digest structure.dump
#

my ( $pdbx_dump_file_1, $pdbx_dump_file_2  ) = @ARGV;

my $atom_site_1;
open( my $fh, "<", $pdbx_dump_file_1 );
while( <$fh> ) {
    $atom_site_1 .= "$_" ;
}
close( $fh );
$atom_site_1 = eval( $atom_site_1 );

my $atom_site_2;
open( $fh, "<", $pdbx_dump_file_2 );
while( <$fh> ) {
    $atom_site_2 .= "$_" ;
}
close( $fh );
$atom_site_2 = eval( $atom_site_2 );

my $parameters = Parameters->new();

print connection_digest( $parameters, $atom_site_1 ), "\n";
print connection_digest( $parameters, $atom_site_2 ), "\n";
