#!/usr/bin/perl

use strict;
use warnings;

use ConnectAtoms qw( connect_atoms );

#
# Unit test: ConnectAtoms::connect_atoms
# Example: ./connect_atoms structure.dump
#

my ( $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my %connected_atoms = %{ connect_atoms( $atom_site ) };

my @atom_coord;
my @parent_atom;
my @child_atom;

for my $parent_id ( keys %connected_atoms ) {
    @parent_atom = ( $parent_id, $connected_atoms{$parent_id}{"label_atom_id"} );
    for my $child_id ( @{ $connected_atoms{$parent_id}{"connections"} } ) {
        @child_atom =
    	    ( $child_id, $connected_atoms{$child_id}{"label_atom_id"} );
        print( "$parent_atom[0] $parent_atom[1]:" );
        print( "$child_atom[0] $child_atom[1]\n" );
    }
}
