#!/usr/bin/perl

use strict;
use warnings;

use ConnectAtoms qw( connection_sequence );
use ForceField::Parameters;

#
# Unit test: ConnectAtoms::connection_sequence
# Example: ./connection_sequence structure
#

my ( $pdbx_dump_file, $start_atom_id, $next_atom_id ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $parameters = Parameters->new();

my $connection_sequence =
    connection_sequence($parameters, $atom_site, $start_atom_id, $next_atom_id);

foreach( @{ $connection_sequence } ) {
    print $_, "\n";
}
