#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;
$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Indent = 1;

use AtomProperties qw( %ATOMS );
use BondProperties qw( covalent_bond_combinations );

#
# Unit test: BondProperties::covalent_bond_combinations
# Example: ./covalent_bond_combinations
#

print Dumper covalent_bond_combinations( \%ATOMS );
