#!/usr/bin/perl

use strict;
use warnings;

use LinearAlgebra qw( create_ref_frame );

#
# Unit test: LinearAlgebra::create_ref_frame.
# Example: ./create_ref_frame atom-coord.dat
#

my ( $atom_coord_file ) = @ARGV;
my @atom_coord;

open( my $fh, "<", $atom_coord_file );
while( <$fh> ){
    push( @atom_coord, grep( /\S/, split( /#.+|\s+/, $_ ) ) );
}
close( $fh );

    # mid-atom      # up-atom       # side-atom
my $local_ref_frame = create_ref_frame(
    $atom_coord[0], $atom_coord[1], $atom_coord[2],   # x-axis
    $atom_coord[3], $atom_coord[4], $atom_coord[5],   # y-axis
    $atom_coord[6], $atom_coord[7], $atom_coord[8] ); # z-axis

for( my $i=0; $i < 3; $i++ ) {
    for( my $j=0; $j < 3; $j++ ) {
	printf( "%.3f ", $local_ref_frame->[$i][$j] );
    }
    print( "\n" );
}
