#!/usr/bin/perl

use strict;
use warnings;

use PDBxParser qw( determine_residue_keys );

#
# Unit test: PDBxParser::determine_residue_keys
# Example: ./determine_residue_keys 1 structure.dump
#

my ( $exclude_dot, $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $residue_unique_keys =
    determine_residue_keys( $atom_site, { 'exclude_dot' => 1 } );

foreach( sort { $a cmp $b } @{ $residue_unique_keys } ) {
    print $_, "\n";
}
