#!/usr/bin/perl

use strict;
use warnings;

use Measure qw( dihedral_angle );

#
# Unit test: Measure::dihedral_angle
# Example: ./dihedral_angle atom-coords.dat
#

my ( $atom_coords_file ) = @ARGV;

my @atom_coords;
open( my $fh, "<", $atom_coords_file );
while( <$fh> ){
    push( @atom_coords, [ grep( /\S/, split( /#.+|\s+/, $_ ) ) ] );
}
close( $fh );

printf( "%.3f\n", dihedral_angle( \@atom_coords ) );
