#!/usr/bin/perl

use strict;
use warnings;

use ForceField::Parameters;
use Measure qw( energy );

my ( $potential, $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $PARAMETERS = Parameters->new();
my $PI = $PARAMETERS->{'_[local]_constants'}{'pi'};

my $potential_energies =
    energy( $atom_site, $potential, $PARAMETERS );

for my $residue_unique_key ( sort keys %{ $potential_energies } ) {
    my @potential_energies =
        sort { $a->atoms->[0]  <=> $b->atoms->[0]  ||
               $a->atoms->[-1] <=> $b->atoms->[-1] ||
               $a->energy_type cmp $b->energy_type }
            @{ $potential_energies->{$residue_unique_key} };
    for my $energy ( @potential_energies ) {
        printf( "%s,%s,%s,%s,%.3f\n",
                $residue_unique_key,
                $energy->energy_type,
                $energy->atoms->[0],
                $energy->atoms->[-1],
                $energy->value );
    }
}
