#!/usr/bin/perl

use strict;
use warnings;

use LinearAlgebra qw( find_euler_angles );

#
# Unit test: LinearAlgebra::find_euler_angles.
# Example: ./find_euler_angles atom-coord.dat
#

my ( $atom_coord_file ) = @ARGV;
my @atom_coord;

open( my $fh, "<", $atom_coord_file );
while( <$fh> ){
    push( @atom_coord, grep( /\S/, split( /#.+|\s+/, $_ ) ) );
}
close( $fh );

my $euler_angles = find_euler_angles(
    [ $atom_coord[0], $atom_coord[1], $atom_coord[2] ],
    [ $atom_coord[3], $atom_coord[4], $atom_coord[5] ],
    [ $atom_coord[6], $atom_coord[7], $atom_coord[8] ] );

print( join( " ", map { sprintf( "%.3f", $_ ) } @{ $euler_angles } ) . "\n" );
