#!/usr/bin/perl

use strict;
use warnings;

use LinearAlgebra qw( flatten );

#
# Unit test: LinearAlgebra::flatten.
# Example: ./flatten matrices.dat
#

my ( $matrix_file ) = @ARGV;

# Evaluates matrices.
my @matrices = ( [] );
open( my $fh, "<", $matrix_file );
while( <$fh> ) {
    if( $_ =~ /^\n$/ ) {
        push( @matrices, [] );
    } else {
        push( @{ $matrices[-1] }, [ split( " ", $_ ) ] );
    }
}
close( $fh );

my $element_list = flatten( \@matrices );
print( join( " ", @{ $element_list } ), "\n" );
