#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib";
use LinearAlgebra qw( flatten );

#
# Unit test: LinearAlgebra::flatten.
#
# Multiplies multiple matrices analytically.
#
# Example: ./flatten example.dat
#

my ( $matrix_file ) = @ARGV;

# Evaluates matrices.
my @matrices = ( [] );

open( my $fh, "<", $matrix_file );
while( <$fh> ) {
    if( $_ =~ /^\n$/ ) {
	push( @matrices, [] );
    } else {
	push( @{ $matrices[-1] }, [ split( " ", $_ ) ] );
    }
}
close( $fh );

my $element_list = flatten( \@matrices );

print( join( " ", @{ $element_list } ), "\n" );
