#!/usr/bin/perl

use strict;
use warnings;

use BondParameters qw( bendable_angles
                       rotatable_bonds
                       stretchable_bonds );
use ForceField::Parameters;
use PDBxParser qw( to_pdbx );
use PseudoAtoms qw( generate_rotamer );
use SidechainModels qw( rotation_translation
                        rotation_translation_new );

#
# Unit test: PseudoAtoms::generate_rotamer
# Example: ./generate_rotamer "12,A,1,." "chi1 0" structure.dump
#

my ( $residue_unique_key, $bond_parameter_values, $pdbx_dump_file,
     $do_angle_bending, $do_bond_torsion, $do_bond_stretching ) = @ARGV;

$do_angle_bending //= 0;
$do_bond_torsion //= 1;
$do_bond_stretching //= 0;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $parameters = Parameters->new();
my $pi = $parameters->{'_[local]_constants'}{'pi'};

bendable_angles( $parameters, $atom_site ) if $do_angle_bending;
rotatable_bonds( $parameters, $atom_site ) if $do_bond_torsion;
stretchable_bonds( $parameters, $atom_site ) if $do_bond_stretching;

rotation_translation_new( $parameters, $atom_site );

# Parses angles for pseudo-rotamers.
my %bond_parameter_values = ( map { $_->[0] => $_->[1] }
                     map { [ split( " ", $_ ) ] }
                     split( "&", $bond_parameter_values ) );
for my $bond_parameter_value ( keys %bond_parameter_values ) {
    $bond_parameter_values{$bond_parameter_value} =~ s/pi/\$pi/g;
    $bond_parameter_values{$bond_parameter_value} =
        eval( $bond_parameter_values{$bond_parameter_value} );
}

my $generated_rotamers =
    generate_rotamer( { 'parameters' => $parameters,
                        'atom_site' => $atom_site,
                        'bond_parameter_values' =>
                            { $residue_unique_key =>
                                  \%bond_parameter_values } } );

%{ $atom_site } = ( %{ $atom_site }, %{ $generated_rotamers } );

my %pdbx =();
$pdbx{'_atom_site'}{'data'} = $atom_site;
$pdbx{'_atom_site'}{'metadata'}{'is_loop'} = 1;
$pdbx{'_atom_site'}{'metadata'}{'type'} = 'indexed';

to_pdbx( \%pdbx );
