#!/usr/bin/perl

use strict;
use warnings;

use LinearAlgebra qw( pi );
use PDBxParser qw( to_pdbx );
use PseudoAtoms qw( generate_library
                    replace_with_rotamer);

my ( $residue_id,
     $residue_chain,
     $residue_entity,
     $residue_alt,
     $conf_model,
     $small_angle,
     $potential,
     $energy_cutoff_atom,
     $energy_cutoff_residue,
     $pdbx_dump_file,
     $threads ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

$small_angle =~ s/pi/pi\(\)/g;

my $rotamer_library =
    generate_library( { "atom_site" => $atom_site,
                        "residue_unique_keys" =>
                            [ "$residue_id,$residue_chain,$residue_entity," .
                              "$residue_alt" ],
                        "small_angle" => eval( $small_angle ),
                        "conf_model" => $conf_model,
                        "interactions"  => $potential,
                        "energy_cutoff_atom" => $energy_cutoff_atom,
                        "energy_cutoff_residue" => $energy_cutoff_residue,
                        "threads" => $threads } );

for my $residue_unique_key ( keys %{ $rotamer_library } ) {
    my $rotamer_id = 1;
    for my $rotamer ( @{ $rotamer_library->{$residue_unique_key} } ) {
        my %rotamer_site = %{ $atom_site };
        replace_with_rotamer( \%rotamer_site,
                              $residue_unique_key,
                              $rotamer->{'angles'} );
        to_pdbx( { 'atom_site' => \%rotamer_site,
                   'data_name' =>
                       "$rotamer_id:" .
                       join( ';',
                             map { "$_:" .
                                   sprintf( '%.3f', $rotamer->{'angles'}{$_} ) }
                             sort keys %{ $rotamer->{'angles'} } ) } );
        $rotamer_id++;
    }
}
