#!/usr/bin/perl

use strict;
use warnings;

use PDBxParser qw( group_unique_residue_keys );

#
# Unit test: PDBxParser::group_unique_residue_keys.
# Example: ./group_unique_residue_keys '18,1,A,.,18,A;18,1,A,A,18,A'
#

@ARGV = ( "-" ) unless @ARGV;
my ( $unique_residue_keys ) = @ARGV;

my @unique_residue_keys = split /;/, $unique_residue_keys;
my $grouped_unique_residue_keys =
    group_unique_residue_keys( \@unique_residue_keys );

for my $group ( @{ $grouped_unique_residue_keys } ) {
    for my $unique_residue_key ( @{ $group } ) {
        print $unique_residue_key, "\n";
    }

    next if $group eq $grouped_unique_residue_keys->[$#{ $grouped_unique_residue_keys } ];

    print "\n";
}
