#!/usr/bin/perl

use strict;
use warnings;

use ForceField::NonBonded qw( h_bond );
use ForceField::Parameters;

my ( $atom_i_id, $atom_j_id, $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $parameters = Parameters->new();

print h_bond( $parameters,
              $atom_site->{$atom_i_id},
              $atom_site->{$atom_j_id},
              { 'atom_site' => $atom_site } ), "\n";
