#!/usr/bin/perl

use strict;
use warnings;

use ForceField::NonBonded qw( h_bond_implicit );

my ( $donor_id, $acceptor_id, $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

print h_bond_implicit( $atom_site->{$donor_id},
                       $atom_site->{$acceptor_id},
                       { 'atom_site' => $atom_site } ), "\n";
