#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib";
use ConnectAtoms qw( hybridization );

#
# Unit test: ConnectAtoms::hybridization
# Example: ./hybridization structure.dump
#

my ( $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

hybridization( $atom_site );

for my $atom_id ( sort keys %{ $atom_site } ) {
    print( $atom_site->{$atom_id}{"label_atom_id"}, "\t",
	   $atom_site->{$atom_id}{"hybridization"}, "\n" );
}
