#!/usr/bin/perl

use strict;
use warnings;

use PDBxParser qw( filter
                   identify_residue_atoms
                   to_pdbx );

#
# Unit test: PDBxParser::identify_residue_atoms
# Example: ./identify_residue_atoms 'A' structure.dump
#

my ( $unique_residue_key, $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $residue_atom_ids = identify_residue_atoms( $atom_site );

to_pdbx( { 'pdbx_data_indexed' =>
               { '_atom_site' =>
                     filter( { 'atom_site' => $atom_site,
                               'include' =>
                                   { 'id' => $residue_atom_ids->{$unique_residue_key} } } ) } } );
