#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;

use PDBxParser_new qw( pdbx_indexed
                       indexed2raw );

$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Indent = 1;

#
# Unit test: PDBxParser::indexed2raw
# Example: ./indexed2raw '_atom_site' structure.cif
#

my ( $data_identifier, $pdbx_file ) = @ARGV;
my @data_identifier = split( ",", $data_identifier );

my $pdbx = pdbx_indexed( $pdbx_file, \@data_identifier );
indexed2raw( $pdbx );

print Dumper $pdbx;
