#!/usr/bin/perl

use strict;
use warnings;

use ForceField::NonBonded qw( general );
use ForceField::Parameters;
use PDBxParser qw( to_pdbx );
use PseudoAtoms qw( lowest_energy_state );

my ( $atom_i_id, $atom_j_ids, $pdbx_dump_file, $parameters ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

$parameters =~ s/\s//g;
my $PARAMETERS = Parameters->new();
$PARAMETERS->set_parameter_values(
    { '_[local]_force_field' =>
          { map { ( split /=/sm, $_ ) } split /,/sxm, $parameters } }
);

printf "%.6f\n",
    lowest_energy_state( $atom_site->{$atom_i_id},
                         [ map { $atom_site->{$_} }
                               ( split /,/, $atom_j_ids ) ],
                         \&general,
                         $PARAMETERS );
