#!/usr/bin/perl

use strict;
use warnings;

use LinearAlgebra qw( matrix_sub );

#
# Unit test: LinearAlgebra::matrix_sub.
# Example: ./matrix_sub matrices.dat
#

my ( $matrix_file ) = @ARGV;
my @matrices = ( [] );

open( my $fh, "<", $matrix_file );
while( <$fh> ) {
    if( $_ =~ /^\n$/ ) {
	push( @matrices, [] );
    } else {
	push( @{ $matrices[-1] }, [ split( " ", $_ ) ] );
    }
}
close( $fh );

my @left_matrix = @{ $matrices[0] };
my @right_matrix = @{ $matrices[1] };

my $matrix_sub = matrix_sub( \@left_matrix, \@right_matrix );
for my $row ( @{ $matrix_sub } ) {
    print( join( " ", @{ $row } ), "\n" );
}
