#!/usr/bin/perl

use strict;
use warnings;

use LinearAlgebra qw( normalize );
use ForceField::Parameters;

#
# Unit test: LinearAlgebra::normalize.
# Example: ./vector_cross vector.dat
#

my ( $vector_file ) = @ARGV;

open( my $fh, "<", $vector_file );
my @rows = <$fh>;
close( $fh );

my $PARAMETERS = Parameters->new();
my $SIG_FIGS_MIN = $PARAMETERS->{'_[local]_constants'}{'sig_figs_min'};

my @vector = map { [ split( " ", $_ ) ] } @rows;

my $vector_normalized = normalize( \@vector );

foreach( @{ $vector_normalized } ) {
    printf $SIG_FIGS_MIN . "\n", $_->[0];
}
