#!/usr/bin/perl

use strict;
use warnings;

use lib "../../lib";
use PDBxParser qw( obtain_atom_site
                   to_pdbx );

#
# Unit test: PDBxParser::obtain_atom_site
# Example: ./obtain_atom_site example.cif
#

@ARGV = ( "-" ) unless @ARGV;

my $atom_site;

foreach my $pdbx_file ( @ARGV ) {
    $atom_site = obtain_atom_site( $pdbx_file );
    to_pdbx( $atom_site );
}
