#!/usr/bin/perl

use strict;
use warnings;

use PDBxParser qw( obtain_pdbx_data
                   to_pdbx );

#
# Unit test: PDBxParser::obtain_pdbx_data
# Example: ./obtain_pdbx_data '_atom_site' structure.cif
#

my ( $category_specifier, $pdbx_file ) = @ARGV;
my @category_specifier = split( ",", $category_specifier );

# my $pdbx_loop_data =
    obtain_pdbx_data( $pdbx_file, { 'categories' => \@category_specifier } );

# to_pdbx( { "pdbx_loops" => $pdbx_loop_data } );
