#!/usr/bin/perl

use strict;
use warnings;

use PDBxParser qw( obtain_pdbx_line_new
                   to_pdbx_new );

#
# Unit test: PDBxParser::obtain_pdbx_line
# Example: ./obtain_pdbx_line '_entry.id' structure.cif
#

my ( $item_specifier, $pdbx_file ) = @ARGV;
my @item_specifier = split( ",", $item_specifier );

my $pdbx_line_data = obtain_pdbx_line_new( $pdbx_file, \@item_specifier );

to_pdbx_new( { 'pdbx_lines' => $pdbx_line_data } );
