#!/usr/bin/perl

use strict;
use warnings;

use PDBxParser qw( obtain_pdbx_data
                   to_pdbx );

#
# Unit test: PDBxParser::obtain_pdbx_data
# Example: ./obtain_pdbx_data '_atom_site' structure.cif
#

my ( $data_identifier, $pdbx_file ) = @ARGV;
my @data_identifier = split( ",", $data_identifier );

$pdbx_file = '-' unless $pdbx_file;

my $pdbx_data =
    obtain_pdbx_data( $pdbx_file, \@data_identifier );

to_pdbx( $pdbx_data );
