#!/usr/bin/perl

use strict;
use warnings;

use PDBxParser qw( obtain_atom_sites
                   to_pdbx );

#
# Unit test: PDBxParser::obtain_atom_site
# Example: ./obtain_atom_sites structure.cif
#

@ARGV = ( "-" ) unless @ARGV;

foreach my $pdbx_file ( @ARGV ) {
    my $atom_sites = obtain_atom_sites( $pdbx_file );
    for my $atom_site ( @{ $atom_sites } ) {
        my %pdbx =();
        $pdbx{'_atom_site'}{'data'} = $atom_site;
        $pdbx{'_atom_site'}{'metadata'}{'is_loop'} = 1;
        $pdbx{'_atom_site'}{'metadata'}{'type'} = 'indexed';
        to_pdbx( \%pdbx );
    }
}
