#!/usr/bin/perl

use strict;
use warnings;

use PDBxParser qw( obtain_pdbx_line
                   to_pdbx );

#
# Unit test: PDBxParser::obtain_pdbx_line
# Example: ./obtain_pdbx_line '_entry.id' structure.cif
#

my ( $item_specifier, $pdbx_file ) = @ARGV;
my @item_specifier = split( ",", $item_specifier );

@ARGV = ( $pdbx_file );

# Slurp whole pdbx file.
my @pdbxs = ();
my $line_counter = 0;
{
    local $/ = '';
    while( <> ) {
        push @pdbxs, map { 'data_' . $_ }
        grep { $_ ne '' }
        split /(?<!\S)data_/, $_;
        $line_counter++;
    }
}

my @pdbx_line_data = ();
for my $pdbx ( @pdbxs ) {
    my $pdbx_line_data =
        obtain_pdbx_line( [ $pdbx ], \@item_specifier );
    push @pdbx_line_data, $pdbx_line_data;
}

to_pdbx( $pdbx_line_data[0] );
