#!/usr/bin/perl

use strict;
use warnings;

use PDBxParser qw( obtain_pdb_atom_site
                   to_pdbx );

#
# Unit test: PDBxParser::obtain_pdb_atom_site
# Example: ./obtain_pdb_atom_site structure.cif
#

@ARGV = ( "-" ) unless @ARGV;

my $atom_site;

foreach my $pdbx_file ( @ARGV ) {
    # $atom_site =
    obtain_pdb_atom_site( $pdbx_file );
    # if( %{ $atom_site } ) {
    #     to_pdbx( { "atom_site" => $atom_site } );
    # }
}
