#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;

use PDBxParser qw( pdbx_raw );

$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Indent = 1;

#
# Unit test: PDBxParser::pdbx_raw
# Example: ./pdbx_raw '_atom_site' structure.cif
#

my ( $data_identifier, $pdbx_file ) = @ARGV;
my @data_identifier = split( ",", $data_identifier );

my $pdbx_raw = pdbx_raw( $pdbx_file, \@data_identifier );

print Dumper $pdbx_raw;
