#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;

use PDBxParser_new qw( pdbx_indexed );

$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Indent = 1;

#
# Unit test: PDBxParser::pdbx_indexed
# Example: ./pdbx_indexed '_atom_site' structure.cif
#

my ( $data_identifier, $pdbx_file ) = @ARGV;
my @data_identifier = split( ",", $data_identifier );

my $pdbx_indexed = pdbx_indexed( $pdbx_file, \@data_identifier );

print Dumper $pdbx_indexed;
