#!/usr/bin/perl

use strict;
use warnings;

use Combinatorics qw( permutation );

#
# Unit test: Combinatorics::permutation
# Example: ./permutation set.dat 3
#

my ( $set_file, $size ) = @ARGV;
my @angles = ( [] );

open( my $fh, "<", $set_file );
while( <$fh> ) {
    if( $_ =~ /^\n$/ ) {
        push( @angles, [] );
    } else {
        push( @{ $angles[-1] }, [ split( " ", $_ ) ] );
    }
}
close( $fh );

@angles = map { $_->[0] } @angles;

# Prints out all possible combinations of angles of list of sets.
my $permuted_list = permutation( $size, [], \@angles, [] );

print( join( " ", @{ $_ } ), "\n" ) for @{ $permuted_list }
