#!/usr/bin/perl

use strict;
use warnings;

use Sampling qw( random_sequence );

#
# Unit test: Sampling::random_sequence.
# Example: ./random_sequence 1,2;3,4 5
#

srand( 23 );

my ( $ranges, $count ) = @ARGV;

my @ranges = ();
for my $range ( split /;/, $ranges ) {
    my ( $start, $end ) = split /,/, $range;
    push @ranges, [ $start, $end ];
}

my $sequence = random_sequence( \@ranges, $count );

print join( ' ', map { join( ',', @{ $_ } ) } @{ $sequence } ), "\n";
