#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;

use PDBxParser qw( pdbx_record
                   record2raw );

$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Indent = 1;

#
# Unit test: PDBxParser::record2raw
# Example: ./record2raw '_atom_site' structure.cif
#

my ( $data_identifier, $pdbx_file ) = @ARGV;
my @data_identifier = split( ",", $data_identifier );

my $pdbx = pdbx_record( $pdbx_file, \@data_identifier );
record2raw( $pdbx );

print Dumper $pdbx;
