#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;
$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Indent = 1;

use PDBxParser qw( related_category_data
                   obtain_pdbx_data
                   to_pdbx );

#
# Unit test: PDBxParser::related_category_data
# Example: ./related_category_data structure.cif
#

my ( $pdbx_file ) = @ARGV;

my $pdbx_data = obtain_pdbx_data( $pdbx_file, [ '_atom_site',
                                                '_[local]_rotamer_angle',
                                                '_[local]_rotamer_energy' ] );

print Dumper
    related_category_data( $pdbx_data,
                           { '_atom_site' => {
                               '_[local]_rotamer_angle' =>
                                   [ { 'keys' => [ 'label_seq_id',
                                                   'label_asym_id',
                                                   'pdbx_PDB_model_num',
                                                   'rotamer_id' ],
                                       'reference_keys' => [ 'label_seq_id',
                                                             'label_asym_id',
                                                             'pdbx_PDB_model_num',
                                                             'label_alt_id' ] } ] } } );
