#!/usr/bin/perl

use strict;
use warnings;

use ForceField::Parameters;
use PDBxParser qw( to_pdbx );
use Moieties qw( replace_with_moiety );

#
# Unit test: Moieties::replace_with_moiety
# Example: ./replace_with_moiety '12,A,1,.' 'SER' structure.dump
#

my ( $residue_unique_key, $moiety, $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $parameters = Parameters->new();

replace_with_moiety( $parameters, $atom_site, $residue_unique_key, $moiety );

my %pdbx =();
$pdbx{'_atom_site'}{'data'} = $atom_site;
$pdbx{'_atom_site'}{'metadata'}{'is_loop'} = 1;
$pdbx{'_atom_site'}{'metadata'}{'is_indexed'} = 1;

to_pdbx( \%pdbx );
