#!/usr/bin/perl

use strict;
use warnings;

use ForceField::Parameters;
use PDBxParser qw( to_pdbx );
use PseudoAtoms qw( replace_with_rotamer );

#
# Unit test: PseudoAtoms::replace_with_rotamer
# Example: ./replace_with_rotamer '12,A,1,.' "chi1 0" structure.dump
#

my ( $residue_unique_key, $angle_values, $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $parameters = Parameters->new();
my $pi = $parameters->{'_[local]_constants'}{'pi'};

# Parses angles for pseudo-rotamers.
my %angle_values = ( map { $_->[0] => $_->[1] }
                     map { [ split( " ", $_ ) ] }
                     split( "&", $angle_values ) );
for my $angle_value ( keys %angle_values ) {
    $angle_values{$angle_value} =~ s/pi/\$pi/g;
    $angle_values{$angle_value} = eval( $angle_values{$angle_value} );
}

replace_with_rotamer($parameters,$atom_site,$residue_unique_key,\%angle_values);

to_pdbx( { "atom_site" => $atom_site } );
