#!/usr/bin/perl

use strict;
use warnings;

use ConnectAtoms qw( retains_connections );
use ForceField::Parameters;

#
# Unit test: ConnectAtoms::retains_connections
# Example: ./retains_connections structure1.dump structure2.dump
#

my ( $pdbx_dump_file_1, $pdbx_dump_file_2  ) = @ARGV;

my $atom_site_1;
open( my $fh, "<", $pdbx_dump_file_1 );
while( <$fh> ) {
    $atom_site_1 .= "$_" ;
}
close( $fh );
$atom_site_1 = eval( $atom_site_1 );

my $atom_site_2;
open( $fh, "<", $pdbx_dump_file_2 );
while( <$fh> ) {
    $atom_site_2 .= "$_" ;
}
close( $fh );
$atom_site_2 = eval( $atom_site_2 );

my $parameters = Parameters->new();

my $retains_connections = retains_connections( $parameters,
                                               $atom_site_1, $atom_site_2 );

if( $retains_connections ) {
    print "Connections are retained.\n";
} else {
    print "Connections are not retained.\n";
}
