#!/usr/bin/perl

use strict;
use warnings;

use Constants qw( $SIG_FIGS );
use Measure qw( rmsd );

#
# Unit test: Measure::rmsd
# Example: ./rmsd atom-coords.dat
#

my ( $atom_coords_file ) = @ARGV;
my @atom_coords = ( [] );

open( my $fh, "<", $atom_coords_file );
while( <$fh> ) {
    if( $_ =~ /^\n$/ ) {
        push( @atom_coords, [] );
    } else {
        push( @{ $atom_coords[-1] }, [ split( " ", $_ ) ] );
    }
}
close( $fh );

printf( "$SIG_FIGS\n", rmsd( @atom_coords ) );
