#!/usr/bin/perl

use strict;
use warnings;

use ForceField::Parameters;
use Measure qw( rmsd_sidechains );

#
# Unit test: Measure::rmsd_sidechains
# Example: ./rmsd_sidechains
#

my ( $pdbx_dump_file_1, $pdbx_dump_file_2 ) = @ARGV;

my $atom_site_1;
open( my $fh1, "<", $pdbx_dump_file_1 );
while( <$fh1> ) {
    $atom_site_1 .= "$_" ;
}
close( $fh1 );
$atom_site_1 = eval( $atom_site_1 );

my $atom_site_2;
open( my $fh2, "<", $pdbx_dump_file_2 );
while( <$fh2> ) {
    $atom_site_2 .= "$_" ;
}
close( $fh2 );
$atom_site_2 = eval( $atom_site_2 );

my $parameters = Parameters->new();

rmsd_sidechains( $parameters, $atom_site_1, $atom_site_2, '86,A,1');
