#!/usr/bin/perl

use strict;
use warnings;

use ConnectAtoms qw( rotatable_bonds );

#
# Unit test: ConnectAtoms::rotatable_bonds
# Example: ./rotatable_bonds structure.dump
#

my ( $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my %rotatable_bonds =
    %{ rotatable_bonds( $atom_site ) };

for my $atom_id ( sort { $a cmp $b } keys( %rotatable_bonds ) ) {
    print( "$atom_site->{$atom_id}{\"label_atom_id\"}: "  );
    foreach( @{ $rotatable_bonds{$atom_id} } ) {
	print( "$atom_site->{$_->[0]}{\"label_atom_id\"}," .
	       "$atom_site->{$_->[1]}{\"label_atom_id\"} " )
    }
    print( "\n" );
}
