#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;

use BondParameters qw( bendable_angles
                       rotatable_bonds
                       stretchable_bonds );
use ForceField::Parameters;
use SidechainModels qw( rotation_translation );

$Data::Dumper::Indent = 1;
$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Deepcopy = 1;
$Data::Dumper::Deparse = 1;

#
# Unit test: SidechainModels::rotation_translation
#                          atom_id
# Example: ./rotation_translation 12 structure.dump 1 0 1
#

my ( $atom_id, $pdbx_dump_file, $include_hetatoms, $do_bond_torsion,
     $do_bond_stretching, $do_angle_bending ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $parameters = Parameters->new();

rotatable_bonds(
    $parameters, $atom_site, { 'include_hetatoms' => $include_hetatoms }
) if $do_bond_torsion;
stretchable_bonds(
    $parameters, $atom_site, { 'include_hetatoms' => $include_hetatoms }
) if $do_bond_stretching;
bendable_angles(
    $parameters, $atom_site, { 'include_hetatoms' => $include_hetatoms }
) if $do_angle_bending;

rotation_translation( $parameters, $atom_site );

print Dumper $atom_site->{$atom_id}{"conformation"};
