#!/usr/bin/perl

use strict;
use warnings;

use SidechainModels qw( rotation_only );

#
# Unit test: SidechainModels::rotation_only
#                          atom_id
# Example: ./rotation_only 12 structure.dump
#

my ( $atom_id, $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $conformation = rotation_only( $atom_site )->{$atom_id}{"conformation"};

for my $matrix_id ( 0..$#{ $conformation } ) {
    for my $row ( @{ $conformation->[$matrix_id] } ) {
	for my $item ( @{ $row } ) {
	    if( $item =~ m/^[+-]?\d+[.]?\d+$/ ) {
	    	printf( "%.3f", $item );
	    } else {
	    	print( $item );
	    }
	    print( " " );
	}
	print( "\n" );
    }
    print( "\n" ) if $matrix_id != $#{ $conformation };
}
