#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;

use ForceField::Parameters;
use SidechainModels qw( rotation_translation );

$Data::Dumper::Indent = 1;
$Data::Dumper::Sortkeys = 1;

#
# Unit test: SidechainModels::rotation_translation
#                          atom_id
# Example: ./rotation_translation 12 structure.dump
#

my ( $atom_id, $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $parameters = Parameters->new();

rotation_translation( $parameters, $atom_site );

print Dumper $atom_site->{$atom_id}{"conformation"};
