#!/usr/bin/perl

use strict;
use warnings;

use BondParameters qw( rotatable_bonds );
use ForceField::Parameters;

#
# Unit test: rotatable_bonds()
# Example: ./rotatable_bonds structure.dump
#

my ( $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $parameters = Parameters->new();
rotatable_bonds( $parameters, $atom_site );

for my $atom_id ( sort { $a cmp $b }
                  grep { defined $atom_site->{$_}{'rotatable_bonds'} }
                  keys %{ $atom_site } ) {
    my $rotatable_bonds = $atom_site->{$atom_id}{'rotatable_bonds'};
    print( "$atom_site->{$atom_id}{\"label_atom_id\"}: "  );
    for my $angle_name ( sort { $rotatable_bonds->{$a}{'order'} <=>
                           $rotatable_bonds->{$b}{'order'} }
                    keys %{ $rotatable_bonds } ) {
        my $first_atom_id = $rotatable_bonds->{$angle_name}{'atom_ids'}[1];
        my $second_atom_id = $rotatable_bonds->{$angle_name}{'atom_ids'}[2];
        print( "$atom_site->{$first_atom_id}{\"label_atom_id\"}," .
               "$atom_site->{$second_atom_id}{\"label_atom_id\"} " );
    }
    print( "\n" );
}
