#!/usr/bin/perl

use strict;
use warnings;

use ForceField::Parameters;
use Sampling qw( sample_angles );

#
# Unit test: Sampling::sample_angles
# Example: ./sample_angles "0-1,3-4" 0.5
#

my $PARAMETERS = Parameters->new();
my $SIG_FIGS_MIN = $PARAMETERS->{'_[local]_constants'}{'sig_figs_min'};

my ( $angle_ranges, $small_angle ) = @ARGV;

my @angle_ranges = ( map { [ $_->[0],  $_->[1] ] }
                     map { [ split( '\.\.', $_ ) ] }
                     split( ',', $angle_ranges ) );

my $sampled_angles =
    sample_angles(  \@angle_ranges, $small_angle, undef, $PARAMETERS );

for my $angle ( @{ $sampled_angles } ) {
    printf( "$SIG_FIGS_MIN ", $angle );
}

print "\n";
