#!/usr/bin/perl

use strict;
use warnings;

use ForceField::Parameters;
use Sampling qw( sample_angles );

#
# Unit test: Sampling::sample_angles
# Example: ./sample_angles "0-1,3-4" 0.5 1 1
#

my $parameters = Parameters->new();
my $sig_figs_min = $parameters->{'_[local]_constants'}{'sig_figs_min'};

my ( $angle_ranges, $small_angle, $inclusive_start, $inclusive_end ) = @ARGV;

my @angle_ranges = ( map { [ $_->[0],  $_->[1] ] }
                     map { [ split( '\.\.', $_ ) ] }
                     split( ',', $angle_ranges ) );

my $sampled_angles =
    sample_angles( $parameters, \@angle_ranges, $small_angle,
                   $inclusive_start, $inclusive_end );

for my $angle ( @{ $sampled_angles } ) {
    printf( "$sig_figs_min ", $angle );
}

print "\n";
