#!/usr/bin/perl

use strict;
use warnings;

use Constants qw( $SIG_FIGS );
use Sampling qw( sample_angles );

#
# Unit test: Sampling::sample_angles
# Example: ./sample_angles "0-1,3-4" 0.5
#

my ( $angle_ranges, $small_angle ) = @ARGV;

my @angle_ranges = ( map { [ $_->[0],  $_->[1] ] }
                     map { [ split( "-", $_ ) ] }
                     split( ",", $angle_ranges ) );

my $sampled_angles = sample_angles(  \@angle_ranges, $small_angle );

for my $angle ( @{ $sampled_angles } ) {
    printf( "$SIG_FIGS\n", $angle );
}
