#!/usr/bin/perl

use strict;
use warnings;

use ForceField::Parameters;
use Grammar::SelectionParser;
use PDBxParser qw( filter_new
                   to_pdbx );

#
# Unit test: Grammar::SelectionParser.
# Example: ./selection_parser 'resname ASP & atoname CA' structure.dump
#

@ARGV = ( "-" ) unless @ARGV;
my ( $selection_command,
     $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $parameters = Parameters->new();

my $selection_parser = new SelectionParser();
my $selected_atom_ids = $selection_parser->parser( $atom_site,
                                                   $selection_command,
                                                   $parameters );

my $selected_atom_site =
    filter_new( $atom_site, { 'include' => { 'id' => $selected_atom_ids } } );

my %pdbx =();
$pdbx{'_atom_site'}{'data'} = $selected_atom_site;
$pdbx{'_atom_site'}{'metadata'}{'is_loop'} = 1;
$pdbx{'_atom_site'}{'metadata'}{'is_indexed'} = 1;
to_pdbx( \%pdbx );
