#!/usr/bin/perl

use strict;
use warnings;

use AtomSite;
use PDBxParser qw( filter
                   to_pdbx );
use Grammar::SelectionParser;

#
# Unit test: Grammar::SelectionParser.
# Example: ./selection_parser 'resname ASP & atoname CA' structure.dump
#

@ARGV = ( "-" ) unless @ARGV;
my ( $selection_command,
     $pdbx_dump_file ) = @ARGV;

my $atom_site;
my $atoms;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atoms .= "$_" ;
}
close( $fh );
$atoms = eval( $atoms );

$atom_site = AtomSite->new();
$atom_site->{'_atoms'} = $atoms;

my $selection_parser = new SelectionParser();
my $selected_atom_site = $selection_parser->parser( $atom_site,
                                                    $selection_command,
                                                    "id" );

to_pdbx( { "atom_site" => $selected_atom_site->{'_atoms'} } );
