#!/usr/bin/perl

use strict;
use warnings;

use AtomProperties qw( sort_atom_names );

#
# Unit test: AtomProperties::sort_atom_names.
# Example: ./sort_by_priority atom_names.dat
#

my ( $atom_names_file ) = @ARGV;

open( my $fh, "<", $atom_names_file );
my @atom_names = <$fh>;
close( $fh );

my ( $atom_names ) =
    map { [ split( " ", $_ ) ] } grep { $_ ne "\n" } @atom_names;

my $sorted_names = sort_atom_names( $atom_names );

print( join( " ", @{ $sorted_names } ), "\n" );
