#!/usr/bin/perl

use strict;
use warnings;

use PDBxParser qw( filter
                   split_by
                   to_pdbx );

#
# Unit test: PDBxParser::split_by.
# Example: ./split_by "pdbx_PDB_model_num,label_alt_id" structure.dump
#          ./split_by "label_alt_id" structure.dump 1
#

@ARGV = ( "-" ) unless @ARGV;
my ( $attributes, $pdbx_dump_file, $append_dot ) = @ARGV;

my @attributes = split( ",", $attributes );

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $split_groups = split_by( { 'atom_site' => $atom_site,
                               'attributes' => \@attributes,
                               'append_dot' => $append_dot } );

foreach( sort keys %{ $split_groups } ) {
    my %pdbx =();
    $pdbx{'_atom_site'}{'data'} =
        filter( { 'atom_site' => $atom_site,
                  'include' => { 'id' => $split_groups->{$_}{'atom_ids'} } } );
    $pdbx{'_atom_site'}{'metadata'}{'is_loop'} = 1;
    $pdbx{'_atom_site'}{'metadata'}{'type'} = 'indexed';

    to_pdbx( \%pdbx );
}
