#!/usr/bin/perl

use strict;
use warnings;

use PDBxParser qw( split_pdbx_file );

#
# Unit test: PDBxParser::split_pdbx_file
# Example: ./split_pdbx_file structure.cif
#

@ARGV = ( "-" ) unless @ARGV;

my $atom_site;

foreach my $pdbx_file ( @ARGV ) {
    my $pdbx_files = split_pdbx_file( $pdbx_file );
    for my $pdbx_file ( @{ $pdbx_files } ) {
        print $pdbx_file;
    }
}
