#!/usr/bin/perl

use strict;
use warnings;

use BondProperties qw( stretchable_bonds );

#
# Unit test: BondProperties::stretchable_bonds
# Example: ./stretchable_bonds structure.dump
#

my ( $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

stretchable_bonds( $atom_site );

my %stretchable_bonds =
    %{ stretchable_bonds( $atom_site ) };

for my $atom_id ( sort { $a cmp $b } keys( %stretchable_bonds ) ) {
    print( "$atom_site->{$atom_id}{\"label_atom_id\"}: "  );
    for my $bond ( sort { $a cmp $b } keys %{ $stretchable_bonds{$atom_id} } ) {
        my $first_atom_id = $stretchable_bonds{$atom_id}{$bond}->[0];
        my $second_atom_id = $stretchable_bonds{$atom_id}{$bond}->[1];
        print( "$atom_site->{$first_atom_id}{\"label_atom_id\"}," .
               "$atom_site->{$second_atom_id}{\"label_atom_id\"} " );
    }
    print( "\n" );
}
