#!/usr/bin/perl

use strict;
use warnings;

use LinearAlgebra qw( switch_ref_frame );

#
# Unit test: LinearAlgebra::switch_ref_frame.
# Example: ./switch_ref_frame atom-coords.dat local
#          ./switch_ref_frame atom-coords.dat global
#

my ( $atom_coords_file, $ref_frame ) = @ARGV;

my @atom_coords = ( [] );

open( my $fh, "<", $atom_coords_file );
while( <$fh> ) {
    if( $_ =~ /^\n$/ ) {
        push( @atom_coords, [] );
    } else {
        push( @{ $atom_coords[-1] }, split( " ", $_ ) );
    }
}
close( $fh );

my ( $ref_frame_coord ) =
    @{ switch_ref_frame( $atom_coords[0],
                         $atom_coords[1],
                         $atom_coords[2],
                         $ref_frame ) };

for my $row ( @{ $ref_frame_coord } ) {
    print( join( "\t", map { sprintf( "%.3f", $_ ) } @{ $row } ), "\n" );
}
