#!/usr/bin/perl

use strict;
use warnings;

use ForceField::Bonded qw( torsion );
use ForceField::Parameters;

my ( $atom_i_id, $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $PARAMETERS = Parameters->new();

print torsion( $atom_i_id, $PARAMETERS, { 'atom_site' => $atom_site } ), "\n";
