#!/usr/bin/perl

use strict;
use warnings;

use ForceField::Bonded qw( torsion_new );
use ForceField::Parameters;

my ( $atom_i_id, $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

my $parameters = Parameters->new();

print torsion_new( $parameters, $atom_i_id, { 'atom_site' => $atom_site } ),"\n";
