#!/usr/bin/perl

use strict;
use warnings;

use AtomInteractions qw( torsion );

my ( $atom_i_id, $pdbx_dump_file ) = @ARGV;

my $atom_site;
open( my $fh, "<", $pdbx_dump_file );
while( <$fh> ) {
    $atom_site .= "$_" ;
}
close( $fh );
$atom_site = eval( $atom_site );

print torsion( $atom_site, $atom_i_id ), "\n";
