#!/usr/bin/perl

use strict;
use warnings;

use LinearAlgebra qw( transpose );

#
# Unit test: LinearAlgebra::transpose
# Example: ./transpose example.dat
#

@ARGV = ( "-" ) unless @ARGV;
my ( $matrix_file ) = @ARGV;

my @matrix;

open( my $fh, "<", $matrix_file );
while( <$fh> ) {
    push( @matrix, [ split( " ", $_ ) ] );
}
close( $fh );

my $transposed_matrix = transpose( \@matrix );

for my $row ( @{ $transposed_matrix } ) {
    print( join( " ", @{ $row } ), "\n" );
}
