#!/usr/bin/perl

use strict;
use warnings;

use LinearAlgebra qw( translation );
use ForceField::Parameters;

#
# Unit test: LinearAlgebra::translation.
# Example: ./translation 1.50 1.50 1.50 # distance in Angstroms.
#

my $parameters = Parameters->new();
my $sig_figs_min = $parameters->{'_[local]_constants'}{'sig_figs_min'};

my ( $x_distance, $y_distance, $z_distance ) = @ARGV;

my $translation = translation( $x_distance, $y_distance, $z_distance );

for( my $i=0; $i < 4; $i++ ) {
    for( my $j=0; $j < 4; $j++ ) {
        printf( "$sig_figs_min ", $translation->[$i][$j] );
    }
    print( "\n" );
}
