#!/usr/bin/perl

use strict;
use warnings;

use Constants qw( $SIG_FIGS_MIN );
use LinearAlgebra qw( translation );

#
# Unit test: LinearAlgebra::translation.
# Example: ./translation 1.50 1.50 1.50 # distance in Angstroms.
#

my ( $x_distance, $y_distance, $z_distance ) = @ARGV;

my $translation = translation( $x_distance, $y_distance, $z_distance );

for( my $i=0; $i < 4; $i++ ) {
    for( my $j=0; $j < 4; $j++ ) {
        printf( "$SIG_FIGS_MIN ", $translation->[$i][$j] );
    }
    print( "\n" );
}
