#!/usr/bin/perl

use strict;
use warnings;

use LinearAlgebra qw( vector_cross );

#
# Unit test: LinearAlgebra::vector_cross.
# Example: ./vector_cross vectors-3d.dat
#

my ( $vector_file ) = @ARGV;

open( my $fh, "<", $vector_file );
my @vector = <$fh>;
close( $fh );

my ( $left_matrix, $right_matrix ) =
    map { [ split( " ", $_ ) ] } grep { $_ ne "\n" } @vector;
my $cross_product = vector_cross( $left_matrix, $right_matrix );
print( join( " ", @{ $cross_product } ), "\n" );
