#!/usr/bin/perl

use strict;
use warnings;

use LinearAlgebra qw( x_axis_rotation );
use ForceField::Parameters;

#
# Unit test: LinearAlgebra::x_axis_rotation.
# Example: ./x_axis_rotation 1.50 # angle in radians.
#

my $PARAMETERS = Parameters->new();
my $SIG_FIGS_MIN = $PARAMETERS->{'_[local]_constants'}{'sig_figs_min'};

my ( $angle ) = @ARGV;

my $x_axis_rotation = x_axis_rotation( $angle );

for( my $i=0; $i < 4; $i++ ) {
    for( my $j=0; $j < 4; $j++ ) {
        printf( "$SIG_FIGS_MIN ", $x_axis_rotation->[$i][$j] );
    }
    print( "\n" );
}
