#!/usr/bin/perl

use strict;
use warnings;

use LinearAlgebra qw( y_axis_rotation );
use ForceField::Parameters;

#
# Unit test: LinearAlgebra::y_axis_rotation.
# Example: ./y_axis_rotation 1.50 # angle in radians.
#

my $parameters = Parameters->new();
my $sig_figs_min = $parameters->{'_[local]_constants'}{'sig_figs_min'};

my ( $angle ) = @ARGV;

my $y_axis_rotation = y_axis_rotation( $angle );

for( my $i=0; $i < 4; $i++ ) {
    for( my $j=0; $j < 4; $j++ ) {
        printf( "$sig_figs_min ", $y_axis_rotation->[$i][$j] );
    }
    print( "\n" );
}
