#!/usr/bin/perl

use strict;
use warnings;

use Constants qw( $SIG_FIGS );
use LinearAlgebra qw( y_axis_rotation );

#
# Unit test: LinearAlgebra::y_axis_rotation.
# Example: ./y_axis_rotation 1.50 # angle in radians.
#

my ( $angle ) = @ARGV;

my $y_axis_rotation = y_axis_rotation( $angle );

for( my $i=0; $i < 4; $i++ ) {
    for( my $j=0; $j < 4; $j++ ) {
        printf( "$SIG_FIGS ", $y_axis_rotation->[$i][$j] );
    }
    print( "\n" );
}
