#!/usr/bin/perl

use strict;
use warnings;

use LinearAlgebra qw( z_axis_rotation );

#
# Unit test: LinearAlgebra::z_axis_rotation.
# Example: ./z_axis_rotation 1.50 # angle in radians.
#

my ( $angle ) = @ARGV;

my $z_axis_rotation = z_axis_rotation( $angle );

for( my $i=0; $i < 4; $i++ ) {
    for( my $j=0; $j < 4; $j++ ) {
	printf( "%.3f ", $z_axis_rotation->[$i][$j] );
    }
    print( "\n" );
}
